/* ═══════════════════════════════════════════════════════════════
   LEARN WORDS — Kosovo-Wörter aus der Vokabelliste
   Automatisch generiert aus Kosovo-Wörter
   ═══════════════════════════════════════════════════════════════ */

const LEARN_WORDS = [
  // ── FAMILJE (70 Wörter) ──
  { id:1, gheg:"familjë / familje", de:"Familie", note:"[GHEG] Tosk: familje", cat:"familje" },
  { id:2, gheg:"nana / nona", de:"Mama", note:"[GHEG] Tosk: nëna", cat:"familje" },
  { id:3, gheg:"babë / baba", de:"Papa", note:"Tosk: babai", cat:"familje" },
  { id:4, gheg:"babi", de:"Papa (Anrede)", note:"[GHEG] verkürzt", cat:"familje" },
  { id:5, gheg:"prindë / prind", de:"Eltern", note:"[GHEG] Tosk: prindërit", cat:"familje" },
  { id:6, gheg:"atë", de:"Vater (formell)", note:"Tosk: ati", cat:"familje" },
  { id:7, gheg:"mëmë", de:"Mutter (formell)", note:"Tosk: mëma", cat:"familje" },
  { id:8, gheg:"djalë", de:"Sohn / Junge", note:"Tosk: djalë", cat:"familje" },
  { id:9, gheg:"çikë", de:"Tochter / Mädchen", note:"[GHEG] Tosk: vajzë", cat:"familje" },
  { id:10, gheg:"vajzë", de:"Mädchen", note:"Auch Tosk", cat:"familje" },
  { id:11, gheg:"vlla", de:"Bruder", note:"[GHEG] Tosk: vëlla", cat:"familje" },
  { id:12, gheg:"vëlla", de:"Bruder (formell)", note:"Tosk-Form, auch in Kosova gehört", cat:"familje" },
  { id:13, gheg:"motër", de:"Schwester", note:"Gleich im Tosk", cat:"familje" },
  { id:14, gheg:"vllazën / vllazni", de:"Brüder", note:"[GHEG] Tosk: vëllezër", cat:"familje" },
  { id:15, gheg:"motra", de:"Schwestern", note:"Tosk: motrat", cat:"familje" },
  { id:16, gheg:"gjysh", de:"Großvater", note:"[GHEG] Tosk: gjysh; Aussprache weicher", cat:"familje" },
  { id:17, gheg:"gjyshe", de:"Großmutter", note:"[GHEG] Tosk: gjyshe", cat:"familje" },
  { id:18, gheg:"gjyshë", de:"Großvater (alternativ)", note:"Tosk: gjyshi", cat:"familje" },
  { id:19, gheg:"hallë", de:"Tante (väterlicherseits)", note:"Tosk: hallë", cat:"familje" },
  { id:20, gheg:"teze", de:"Tante (mütterlicherseits)", note:"Tosk: teze", cat:"familje" },
  { id:21, gheg:"xhajë / xhaja", de:"Onkel (väterlicherseits)", note:"[GHEG] Tosk: xhaxha", cat:"familje" },
  { id:22, gheg:"dajë / daja", de:"Onkel (mütterlicherseits)", note:"Tosk: daja", cat:"familje" },
  { id:23, gheg:"nip", de:"Neffe / Enkel", note:"Tosk: nip", cat:"familje" },
  { id:24, gheg:"mbë", de:"Nichte / Enkelin", note:"[GHEG] Tosk: mbesë", cat:"familje" },
  { id:25, gheg:"kunat / kunati", de:"Schwager", note:"Tosk: kunati", cat:"familje" },
  { id:26, gheg:"kunatë", de:"Schwägerin", note:"Tosk: kunata", cat:"familje" },
  { id:27, gheg:"vjehërr", de:"Schwiegervater", note:"Tosk: vjehrri", cat:"familje" },
  { id:28, gheg:"vjehërrë", de:"Schwiegermutter", note:"[GHEG] Tosk: vjehrra", cat:"familje" },
  { id:29, gheg:"dhëndër / dhëndri", de:"Bräutigam / Schwiegersohn", note:"Tosk: dhëndri", cat:"familje" },
  { id:30, gheg:"nusja", de:"Braut / Schwiegertochter", note:"[GHEG] Tosk: nusja", cat:"familje" },
  { id:31, gheg:"i afërm / e afërme", de:"Verwandter", note:"Tosk: i afërm", cat:"familje" },
  { id:32, gheg:"farefis / farefisi", de:"Verwandtschaft", note:"Tosk: farefisi", cat:"familje" },
  { id:33, gheg:"fëmijë", de:"Kind", note:"[GHEG] Aussprache fëmijë / fëmi", cat:"familje" },
  { id:34, gheg:"fëmi", de:"Kind (verkürzt)", note:"[GHEG] Tosk: fëmijë", cat:"familje" },
  { id:35, gheg:"fëmijët", de:"Kinder (Pl.)", note:"Tosk: fëmijët", cat:"familje" },
  { id:36, gheg:"të porsalindur", de:"Neugeborenes", note:"Tosk: i porsalindur", cat:"familje" },
  { id:37, gheg:"binjakë", de:"Zwillinge", note:"Tosk: binjakët", cat:"familje" },
  { id:38, gheg:"jetim", de:"Waise", note:"Tosk: jetim", cat:"familje" },
  { id:39, gheg:"bashkëshort", de:"Ehemann", note:"Tosk: bashkëshort", cat:"familje" },
  { id:40, gheg:"bashkëshorte", de:"Ehefrau", note:"Tosk: bashkëshorte", cat:"familje" },
  { id:41, gheg:"burrë", de:"Mann / Ehemann", note:"Tosk: burrë", cat:"familje" },
  { id:42, gheg:"grue / grua", de:"Frau / Ehefrau", note:"[GHEG] Tosk: grua", cat:"familje" },
  { id:43, gheg:"çupë", de:"junges Mädchen", note:"[GHEG] Tosk: vajzë e re", cat:"familje" },
  { id:44, gheg:"djalosh / djaloshi", de:"Jüngling / junger Mann", note:"Tosk: djalosh", cat:"familje" },
  { id:45, gheg:"plak", de:"alter Mann", note:"Tosk: plak", cat:"familje" },
  { id:46, gheg:"plakë", de:"alte Frau", note:"Tosk: plakë", cat:"familje" },
  { id:47, gheg:"i ri / e re", de:"jung", note:"Tosk: i ri / e re", cat:"familje" },
  { id:48, gheg:"fëmijëri", de:"Kindheit", note:"Tosk: fëmijëri", cat:"familje" },
  { id:49, gheg:"martesë", de:"Hochzeit / Ehe", note:"[GHEG] Tosk: martesë", cat:"familje" },
  { id:50, gheg:"martohem", de:"heiraten", note:"Tosk: martohem", cat:"familje" },
  { id:51, gheg:"fejesë", de:"Verlobung", note:"Tosk: fejesë", cat:"familje" },
  { id:52, gheg:"i fejuar / e fejuar", de:"verlobt", note:"Tosk: i fejuar", cat:"familje" },
  { id:53, gheg:"divorc / shkurorëzim", de:"Scheidung", note:"Tosk: divorc", cat:"familje" },
  { id:54, gheg:"vejan / vejanë", de:"Witwer", note:"Tosk: vejan", cat:"familje" },
  { id:55, gheg:"vejushë", de:"Witwe", note:"Tosk: vejushë", cat:"familje" },
  { id:56, gheg:"mik / miku", de:"Freund", note:"Tosk: miku", cat:"familje" },
  { id:57, gheg:"mike", de:"Freundin", note:"Tosk: mikja", cat:"familje" },
  { id:58, gheg:"shok / shoku", de:"Freund (Kumpel)", note:"[GHEG] Tosk: shoku", cat:"familje" },
  { id:59, gheg:"shoqe", de:"Freundin (Kumpelin)", note:"Tosk: shoqja", cat:"familje" },
  { id:60, gheg:"fqinj / fqinji", de:"Nachbar", note:"Tosk: fqinji", cat:"familje" },
  { id:61, gheg:"fqinjë", de:"Nachbarin", note:"Tosk: fqinja", cat:"familje" },
  { id:62, gheg:"i huaj / e huaj", de:"Fremder", note:"Tosk: i huaj", cat:"familje" },
  { id:63, gheg:"gjaku", de:"Blut(sverwandter)", note:"Tosk: gjak", cat:"familje" },
  { id:64, gheg:"trashëgim", de:"Erbschaft", note:"Tosk: trashëgim", cat:"familje" },
  { id:65, gheg:"trashëgimtar", de:"Erbe", note:"Tosk: trashëgimtar", cat:"familje" },
  { id:66, gheg:"morrigji", de:"Ohnmacht", note:"Tosk: morrigji (auch regional)", cat:"familje" },
  { id:67, gheg:"mbarështim", de:"Zucht / Familie gründen", note:"Tosk: mbarështim", cat:"familje" },
  { id:68, gheg:"shtëpi / shpi", de:"Haushalt / Familie", note:"[GHEG] shpi — Tosk: shtëpi", cat:"familje" },
  { id:69, gheg:"mbajtës i familjes", de:"Familienernährer", note:"Tosk: mbajtës", cat:"familje" },
  { id:70, gheg:"jorganxhi", de:"Bettdeckenmacher (Metapher: Familienvater)", note:"[GHEG] regional", cat:"familje" },
  // ── SCHIMPFWÖRTER — T'SHARA (100 Wörter) ──
  // ── Milde Schimpfwörter ──
  { id:823, gheg:"budalla", de:"Dummkopf", note:"Tosk: budalla; sehr geläufig", cat:"schimpf" },
  { id:824, gheg:"trashaman", de:"Idiot / Depp", note:"Tosk: trashaman", cat:"schimpf" },
  { id:825, gheg:"hajvan", de:"Dummkopf (wörtl. Tier)", note:"Tosk: hajvan; aus dem Türkischen", cat:"schimpf" },
  { id:826, gheg:"gomar", de:"Esel (Schimpfwort)", note:"Tosk: gomar; auch 'stur'", cat:"schimpf" },
  { id:827, gheg:"mendjelehtë", de:"Schwachsinnig", note:"Tosk: mendjelehtë; wörtl. 'leichter Verstand'", cat:"schimpf" },
  { id:828, gheg:"i çmendur / e çmendur", de:"Verrückt", note:"Tosk: i çmendur", cat:"schimpf" },
  { id:829, gheg:"matuf", de:"Bescheuert / verrückt", note:"[GHEG] typisch Kosovo-Ausdruck", cat:"schimpf" },
  { id:830, gheg:"batakçi", de:"Betrüger", note:"Tosk: batakçi; aus dem Türkischen", cat:"schimpf" },
  { id:831, gheg:"rrugaç", de:"Flegel / unhöflicher Mensch", note:"Tosk: rrugaç", cat:"schimpf" },
  { id:832, gheg:"i vrazhdë / e vrazhdë", de:"Grob / unhöflich", note:"Tosk: i vrazhdë", cat:"schimpf" },
  { id:833, gheg:"i keq / e keqe", de:"Böse / gemein", note:"Tosk: i keq", cat:"schimpf" },
  { id:834, gheg:"i poshtër / e poshtër", de:"Gemein / niederträchtig", note:"Tosk: i poshtër", cat:"schimpf" },
  { id:835, gheg:"i ulët / e ulët", de:"Niederträchtig", note:"Tosk: i ulët; wörtl. 'niedrig'", cat:"schimpf" },
  { id:836, gheg:"i pacipë / e pacipë", de:"Unverschämt / frech", note:"Tosk: i pacipë", cat:"schimpf" },
  { id:837, gheg:"i pafytyrë / e pafytyrë", de:"Schamlos", note:"Tosk: i pafytyrë", cat:"schimpf" },
  { id:838, gheg:"pa nder", de:"Ehrlos", note:"Tosk: pa nder; schwere Beleidigung im Balkan", cat:"schimpf" },
  { id:839, gheg:"gënjeshtar / gënjeshtare", de:"Lügner", note:"Tosk: gënjeshtar", cat:"schimpf" },
  { id:840, gheg:"lajkatar", de:"Speichellecker", note:"Tosk: lajkatar", cat:"schimpf" },
  { id:841, gheg:"pisk", de:"Armselig / erbärmlich", note:"[GHEG] Kosovo-Ausdruck", cat:"schimpf" },
  { id:842, gheg:"i marrë / e marrë", de:"Bescheuert / verblödet", note:"Tosk: i marrë", cat:"schimpf" },
  // ── Mittelstarke Schimpfwörter ──
  { id:843, gheg:"mut / muti", de:"Scheiße", note:"Tosk: mut; universell", cat:"schimpf" },
  { id:844, gheg:"bythë / bytha", de:"Arsch", note:"[GHEG] Kosovo sagt 'bythë'", cat:"schimpf" },
  { id:845, gheg:"bythqirë", de:"Arschloch", note:"[GHEG] Tosk: bythëqirë", cat:"schimpf" },
  { id:846, gheg:"qelbësi / qelbësirë", de:"Stinker / Dreckskerl", note:"Tosk: qelbësi", cat:"schimpf" },
  { id:847, gheg:"pisllëk", de:"Dreck / Schweinerei", note:"Tosk: pisllëk", cat:"schimpf" },
  { id:848, gheg:"pisatar", de:"Dreckiger Mensch", note:"Tosk: pisatar", cat:"schimpf" },
  { id:849, gheg:"i ndyrë / e ndyrë", de:"Dreckig / schmutzig (Schimpf)", note:"Tosk: i ndyrë", cat:"schimpf" },
  { id:850, gheg:"neveri", de:"Ekel", note:"Tosk: neveri", cat:"schimpf" },
  { id:851, gheg:"i neveritshëm / e neveritshme", de:"Ekelhaft", note:"Tosk: i neveritshëm", cat:"schimpf" },
  { id:852, gheg:"dreq / dreqi", de:"Teufel / verdammt", note:"Tosk: dreq; Alltagsfluch", cat:"schimpf" },
  { id:853, gheg:"djall / djalli", de:"Satan / Teufel", note:"Tosk: djall", cat:"schimpf" },
  { id:854, gheg:"në dreq", de:"Zur Hölle!", note:"Tosk: në dreq", cat:"schimpf" },
  { id:855, gheg:"horr / horri", de:"Schurke / Abschaum", note:"Tosk: horr", cat:"schimpf" },
  { id:856, gheg:"horr i ndyrë", de:"Dreckiger Schurke", note:"Tosk: horr i ndyrë", cat:"schimpf" },
  { id:857, gheg:"shëmtim", de:"Bastard (wörtl. Schändung)", note:"Tosk: shëmtim", cat:"schimpf" },
  { id:858, gheg:"kopil", de:"Bastard", note:"Tosk: kopil", cat:"schimpf" },
  { id:859, gheg:"tradhtar / tradhtare", de:"Verräter", note:"Tosk: tradhtar", cat:"schimpf" },
  { id:860, gheg:"mashtrues", de:"Betrüger", note:"Tosk: mashtrues", cat:"schimpf" },
  { id:861, gheg:"hajdut", de:"Dieb", note:"Tosk: hajdut", cat:"schimpf" },
  { id:862, gheg:"dembel", de:"Faulpelz", note:"Tosk: dembel; aus dem Türkischen", cat:"schimpf" },
  { id:863, gheg:"përtac", de:"Faulenzer", note:"Tosk: përtac", cat:"schimpf" },
  { id:864, gheg:"llafazan", de:"Schwätzer", note:"Tosk: llafazan", cat:"schimpf" },
  { id:865, gheg:"kriminel", de:"Verbrecher", note:"Tosk: kriminel", cat:"schimpf" },
  { id:866, gheg:"i sëmurë / e sëmurë", de:"Krank (im Kopf)", note:"Tosk: i sëmurë; abwertend", cat:"schimpf" },
  { id:867, gheg:"dreq e bëftë", de:"Hol's der Teufel", note:"Tosk: dreq e bëftë; Fluch", cat:"schimpf" },
  { id:868, gheg:"të vraftë Zoti", de:"Gott soll dich töten", note:"Tosk: të vraftë Zoti; schwerer Fluch", cat:"schimpf" },
  // ── Starke Schimpfwörter (sexuell, vulgär) ──
  { id:869, gheg:"kar / kari", de:"Schwanz (vulgär)", note:"Tosk: kar; Alltagsbeleidigung", cat:"schimpf" },
  { id:870, gheg:"pidh / pidhi", de:"Fotze (vulgär)", note:"Tosk: pidh; derb", cat:"schimpf" },
  { id:871, gheg:"kurvë / kurva", de:"Hure", note:"Tosk: kurvë", cat:"schimpf" },
  { id:872, gheg:"djalë kurve", de:"Hurensohn", note:"[GHEG] Tosk: bir kurve", cat:"schimpf" },
  { id:873, gheg:"bir kurve", de:"Hurensohn (Tosk)", note:"Tosk-Form, auch in Kosovo gehört", cat:"schimpf" },
  { id:874, gheg:"biç kurve", de:"Hurensohn (Gheg)", note:"[GHEG] typisch Kosovo; 'biç' = Junge", cat:"schimpf" },
  { id:875, gheg:"kurvar", de:"Hurenbock", note:"Tosk: kurvar", cat:"schimpf" },
  { id:876, gheg:"lavire", de:"Flittchen / Schlampe", note:"Tosk: lavire", cat:"schimpf" },
  { id:877, gheg:"kari i babës", de:"Vaters Schwanz", note:"[GHEG] schwere Beleidigung", cat:"schimpf" },
  { id:878, gheg:"kari i nënës", de:"Mutters Schwanz", note:"[GHEG] schwere Beleidigung", cat:"schimpf" },
  // ── Sehr starke Kraftausdrücke (Gheg Kosovo) ──
  { id:879, gheg:"qifsha nënën", de:"Fick deine Mutter", note:"[GHEG] Tosk: qifsha nënën; schwerster Fluch", cat:"schimpf" },
  { id:880, gheg:"qifsha babën", de:"Fick deinen Vater", note:"[GHEG] Tosk: qifsha babën", cat:"schimpf" },
  { id:881, gheg:"qifsha robt", de:"Fick deine Familie", note:"[GHEG] 'robt' = Verwandte; Kosovo-spezifisch", cat:"schimpf" },
  { id:882, gheg:"qifsha motrën", de:"Fick deine Schwester", note:"[GHEG] Tosk: qifsha motrën", cat:"schimpf" },
  { id:883, gheg:"t'a qifsha nonën", de:"Fick deine Mutter (Gheg)", note:"[GHEG] 'nonë' = Mutter auf Gheg", cat:"schimpf" },
  { id:884, gheg:"t'a qifsha", de:"Fick dich", note:"[GHEG] Kurzform", cat:"schimpf" },
  { id:885, gheg:"nanën të qifsha", de:"Deine Mutter gefickt", note:"[GHEG] Gheg-Variante", cat:"schimpf" },
  { id:886, gheg:"t'a qifsha tërë familjen", de:"Fick deine ganze Familie", note:"[GHEG] Kosovo-Ausdruck", cat:"schimpf" },
  { id:887, gheg:"s'të ka marrë nënë", de:"Bastard (wörtl. keine Mutter geboren)", note:"[GHEG] schwere Beleidigung", cat:"schimpf" },
  { id:888, gheg:"more kar", de:"Du Wichser (Alter Schwanz)", note:"[GHEG] 'more' = Anredepartikel Gheg", cat:"schimpf" },
  { id:889, gheg:"bre mut", de:"Du Scheißkerl", note:"[GHEG] 'bre' = Anredepartikel Kosovo", cat:"schimpf" },
  { id:890, gheg:"o bythqirë", de:"Du Arschloch", note:"[GHEG] Kosovo: 'o' = Anrede", cat:"schimpf" },
  { id:891, gheg:"ik mor", de:"Verpiss dich!", note:"[GHEG] 'mor' = männl. Anredepartikel", cat:"schimpf" },
  { id:892, gheg:"ik që këtu", de:"Hau ab!", note:"Tosk: ik që këtu", cat:"schimpf" },
  { id:893, gheg:"zhduku", de:"Verschwinde!", note:"[GHEG] Tosk: zhduku", cat:"schimpf" },
  { id:894, gheg:"s'vlen asgjë", de:"Nichts wert / taugt nichts", note:"[GHEG] Tosk: s'vlen asgjë", cat:"schimpf" },
  { id:895, gheg:"s'ke të bë", de:"Du taugst nichts", note:"[GHEG] Kosovo-Ausdruck", cat:"schimpf" },
  { id:896, gheg:"mos shih në sy", de:"Schamloser", note:"[GHEG] wörtl. 'schau nicht in die Augen'", cat:"schimpf" },
  { id:897, gheg:"rruga e dreqit", de:"Weg zur Hölle", note:"Tosk: rruga e dreqit; Fluch", cat:"schimpf" },
  { id:898, gheg:"shpirt i keq", de:"Böse Seele", note:"Tosk: shpirt i keq", cat:"schimpf" },
  { id:899, gheg:"shpirti i djallit", de:"Seele des Teufels", note:"Tosk: shpirti i djallit", cat:"schimpf" },
  { id:900, gheg:"të daltë dreqi", de:"Der Teufel soll dich holen", note:"Tosk: të daltë dreqi", cat:"schimpf" },
  { id:901, gheg:"të hajë dheu", de:"Die Erde soll dich verschlucken", note:"Tosk: të hajë dheu; alter Fluch", cat:"schimpf" },
  { id:902, gheg:"mos paç bekim", de:"Keinen Segen haben", note:"Tosk: mos paç bekim; Fluch", cat:"schimpf" },
  { id:903, gheg:"hajde qíje", de:"Geh fick dich", note:"[GHEG] 'qíje' = fick dich (Gheg)", cat:"schimpf" },
  { id:904, gheg:"qifshu / qiju", de:"Fick dich selbst", note:"[GHEG] reflexive Form", cat:"schimpf" },
  { id:905, gheg:"qifsha dreqin", de:"Fick den Teufel", note:"[GHEG] Tosk: qifsha dreqin", cat:"schimpf" },
  { id:906, gheg:"t'u qifsha gojën", de:"Fick dein Maul", note:"[GHEG] Kosovo-Ausdruck", cat:"schimpf" },
  { id:907, gheg:"s'ke nder", de:"Du hast keine Ehre", note:"[GHEG] schwere Beleidigung im Balkan", cat:"schimpf" },
  // ── SHTEPI (90 Wörter) ──
  { id:71, gheg:"shpi", de:"Haus", note:"[GHEG] Tosk: shtëpi", cat:"shtepi" },
  { id:72, gheg:"shtëpi", de:"Haus (formell)", note:"Tosk: shtëpi", cat:"shtepi" },
  { id:73, gheg:"dhomë", de:"Zimmer", note:"[GHEG] Tosk: dhomë", cat:"shtepi" },
  { id:74, gheg:"odë / oda", de:"Stube / Wohnzimmer", note:"[GHEG] Tosk: dhomë ndenjeje", cat:"shtepi" },
  { id:75, gheg:"kuzhinë", de:"Küche", note:"Tosk: kuzhinë", cat:"shtepi" },
  { id:76, gheg:"banjë", de:"Badezimmer", note:"Tosk: banjë", cat:"shtepi" },
  { id:77, gheg:"tualet / nevojtore", de:"Toilette", note:"Tosk: tualet", cat:"shtepi" },
  { id:78, gheg:"dhomë gjumi", de:"Schlafzimmer", note:"Tosk: dhomë gjumi", cat:"shtepi" },
  { id:79, gheg:"dhomë ndejëse / ndejëse", de:"Wohnzimmer", note:"[GHEG] Tosk: dhomë ndenjeje", cat:"shtepi" },
  { id:80, gheg:"ballkon", de:"Balkon", note:"Tosk: ballkon", cat:"shtepi" },
  { id:81, gheg:"tarracë", de:"Terrasse", note:"Tosk: tarracë", cat:"shtepi" },
  { id:82, gheg:"oborr / oborri", de:"Hof / Garten", note:"Tosk: oborr", cat:"shtepi" },
  { id:83, gheg:"kopsht", de:"Garten", note:"Tosk: kopsht", cat:"shtepi" },
  { id:84, gheg:"dyer / dera", de:"Tür", note:"[GHEG] Tosk: derë; dyert (Pl.)", cat:"shtepi" },
  { id:85, gheg:"dritare", de:"Fenster", note:"Tosk: dritare", cat:"shtepi" },
  { id:86, gheg:"mur / muri", de:"Wand", note:"Tosk: mur", cat:"shtepi" },
  { id:87, gheg:"mure", de:"Wände (Pl.)", note:"Tosk: muret", cat:"shtepi" },
  { id:88, gheg:"çati", de:"Dach", note:"Tosk: çati", cat:"shtepi" },
  { id:89, gheg:"tavan", de:"Decke (Zimmerdecke)", note:"Tosk: tavan", cat:"shtepi" },
  { id:90, gheg:"kat", de:"Stockwerk / Etage", note:"Tosk: kat", cat:"shtepi" },
  { id:91, gheg:"përdhesë / përdhe", de:"Erdgeschoss", note:"[GHEG] Tosk: përdhesë", cat:"shtepi" },
  { id:92, gheg:"shkallë", de:"Treppe", note:"Tosk: shkallë", cat:"shtepi" },
  { id:93, gheg:"shkallët", de:"Treppe (Pl.)", note:"Tosk: shkallët", cat:"shtepi" },
  { id:94, gheg:"bodrum", de:"Keller", note:"Tosk: bodrum", cat:"shtepi" },
  { id:95, gheg:"papafingo", de:"Dachboden", note:"Tosk: papafingo", cat:"shtepi" },
  { id:96, gheg:"garazh / garazha", de:"Garage", note:"Tosk: garazh", cat:"shtepi" },
  { id:97, gheg:"korridor", de:"Korridor", note:"Tosk: korridor", cat:"shtepi" },
  { id:98, gheg:"holl / holli", de:"Flur / Diele", note:"[GHEG] Tosk: holl", cat:"shtepi" },
  { id:99, gheg:"portë / porta", de:"Pforte / Tor", note:"Tosk: portë", cat:"shtepi" },
  { id:100, gheg:"gardh / gardhi", de:"Zaun", note:"Tosk: gardh", cat:"shtepi" },
  { id:101, gheg:"kthinë", de:"kleine Kammer", note:"Tosk: kthinë", cat:"shtepi" },
  { id:102, gheg:"qilim / qilimi", de:"Teppich", note:"Tosk: qilim", cat:"shtepi" },
  { id:103, gheg:"shtrim / shtrimi", de:"Bodenbelag", note:"Tosk: shtrim", cat:"shtepi" },
  { id:104, gheg:"dysheme", de:"Fußboden", note:"Tosk: dysheme", cat:"shtepi" },
  { id:105, gheg:"mobilje", de:"Möbel", note:"Tosk: mobilje", cat:"shtepi" },
  { id:106, gheg:"shtrat", de:"Bett", note:"Tosk: shtrat", cat:"shtepi" },
  { id:107, gheg:"mbulesë / mbulesa", de:"Bettdecke", note:"Tosk: mbulesë", cat:"shtepi" },
  { id:108, gheg:"jastëk", de:"Kissen", note:"Tosk: jastëk", cat:"shtepi" },
  { id:109, gheg:"çarçaf", de:"Bettlaken", note:"Tosk: çarçaf", cat:"shtepi" },
  { id:110, gheg:"batanije", de:"Wolldecke", note:"Tosk: batanije", cat:"shtepi" },
  { id:111, gheg:"jorgan", de:"Steppdecke", note:"[GHEG] Tosk: jorgan", cat:"shtepi" },
  { id:112, gheg:"tryezë", de:"Tisch", note:"[GHEG] Tosk: tryezë", cat:"shtepi" },
  { id:113, gheg:"masa", de:"Tisch (regional, best. Form)", note:"[GHEG] Grundform masë = Maß; bestimmte Form \"masa\" kann regional Tisch bedeuten", cat:"shtepi" },
  { id:114, gheg:"karrige / karrigja", de:"Stuhl", note:"Tosk: karrige", cat:"shtepi" },
  { id:115, gheg:"kolltuk", de:"Sessel", note:"Tosk: kolltuk", cat:"shtepi" },
  { id:116, gheg:"divan / divani", de:"Sofa / Couch", note:"Tosk: divan", cat:"shtepi" },
  { id:117, gheg:"kanape", de:"Sofa (Lehnwort)", note:"Tosk: kanape", cat:"shtepi" },
  { id:118, gheg:"dollap", de:"Schrank", note:"Tosk: dollap", cat:"shtepi" },
  { id:119, gheg:"dollap i vogël", de:"kleiner Schrank", note:"Tosk: dollap i vogël", cat:"shtepi" },
  { id:120, gheg:"komodë / komoda", de:"Kommode", note:"Tosk: komodë", cat:"shtepi" },
  { id:121, gheg:"krevat", de:"Bettgestell", note:"[GHEG] Tosk: krevat", cat:"shtepi" },
  { id:122, gheg:"veshëse / veshësja", de:"Kleiderbügel", note:"Tosk: varëse rrobash", cat:"shtepi" },
  { id:123, gheg:"pasqyrë / pasqyra", de:"Spiegel", note:"Tosk: pasqyrë", cat:"shtepi" },
  { id:124, gheg:"rahatllëk", de:"Komfort / Bequemlichkeit", note:"[GHEG] türk. rahatlık; NICHT Schublade (sirtar)!", cat:"shtepi" },
  { id:125, gheg:"sirtar", de:"Schublade", note:"Tosk: sirtar", cat:"shtepi" },
  { id:126, gheg:"oxhak", de:"Kamin", note:"Tosk: oxhak", cat:"shtepi" },
  { id:127, gheg:"soba", de:"Ofen", note:"[GHEG] Tosk: sobë", cat:"shtepi" },
  { id:128, gheg:"radiatori", de:"Heizkörper", note:"Tosk: radiator", cat:"shtepi" },
  { id:129, gheg:"kondicioner", de:"Klimaanlage", note:"Tosk: kondicioner", cat:"shtepi" },
  { id:130, gheg:"abazhur / abazhuri", de:"Lampenschirm", note:"Tosk: abazhur", cat:"shtepi" },
  { id:131, gheg:"llambë / llamba", de:"Lampe", note:"Tosk: llambë", cat:"shtepi" },
  { id:132, gheg:"dritë", de:"Licht", note:"Tosk: dritë", cat:"shtepi" },
  { id:133, gheg:"kyç / kyçi", de:"Schloss", note:"Tosk: kyç", cat:"shtepi" },
  { id:134, gheg:"çelës", de:"Schlüssel", note:"Tosk: çelës", cat:"shtepi" },
  { id:135, gheg:"shtëpi me qera", de:"Mietwohnung / -haus", note:"Tosk: shtëpi me qira", cat:"shtepi" },
  { id:136, gheg:"shtëpi private", de:"Eigenheim", note:"Tosk: shtëpi private", cat:"shtepi" },
  { id:137, gheg:"ndërtesë", de:"Gebäude", note:"Tosk: ndërtesë", cat:"shtepi" },
  { id:138, gheg:"apartament", de:"Wohnung", note:"Tosk: apartament", cat:"shtepi" },
  { id:139, gheg:"qira / qeraja", de:"Miete", note:"[GHEG] Tosk: qira", cat:"shtepi" },
  { id:140, gheg:"faturë", de:"Rechnung", note:"Tosk: faturë", cat:"shtepi" },
  { id:141, gheg:"rrymë", de:"Strom", note:"Tosk: rrymë", cat:"shtepi" },
  { id:142, gheg:"ujë", de:"Wasser (Leitung)", note:"Tosk: ujë", cat:"shtepi" },
  { id:143, gheg:"gaz", de:"Gas", note:"Tosk: gaz", cat:"shtepi" },
  { id:144, gheg:"ngrohje / ngrohja", de:"Heizung", note:"Tosk: ngrohje", cat:"shtepi" },
  { id:145, gheg:"ngrohje qendrore", de:"Zentralheizung", note:"Tosk: ngrohje qendrore", cat:"shtepi" },
  { id:146, gheg:"ajër", de:"Luft", note:"Tosk: ajër", cat:"shtepi" },
  { id:147, gheg:"pastrim / pastrimi", de:"Reinigung", note:"Tosk: pastrim", cat:"shtepi" },
  { id:148, gheg:"i marrë / e marrë", de:"verrückt / wahnsinnig", note:"[GHEG] Partizip von marr; Tosk: i marrë (nicht: schmutzig!)", cat:"shtepi" },
  { id:149, gheg:"i ndyrë", de:"schmutzig", note:"Tosk: i ndyrë", cat:"shtepi" },
  { id:150, gheg:"i pastër / e pastër", de:"sauber", note:"Tosk: i pastër", cat:"shtepi" },
  { id:151, gheg:"higjienë", de:"Hygiene", note:"[GHEG] Tosk: higjienë", cat:"shtepi" },
  { id:152, gheg:"çorape / çorapja", de:"Socken (Plural von çorap)", note:"[GHEG] ACHTUNG: çorape bedeutet Socken, NICHT Wasserhahn! Tosk: çorape (gleich)", cat:"shtepi" },
  { id:153, gheg:"rubinet", de:"Wasserhahn", note:"Tosk: rubinet", cat:"shtepi" },
  { id:154, gheg:"lavaman", de:"Waschbecken", note:"Tosk: lavaman", cat:"shtepi" },
  { id:155, gheg:"vaskë", de:"Badewanne", note:"Tosk: vaskë", cat:"shtepi" },
  { id:156, gheg:"dush / dushi", de:"Dusche", note:"Tosk: dush", cat:"shtepi" },
  { id:157, gheg:"perde / perdet", de:"Vorhang", note:"Tosk: perde", cat:"shtepi" },
  { id:158, gheg:"qilim", de:"Teppich", note:"[GHEG] Tosk: qilim", cat:"shtepi" },
  { id:159, gheg:"mbulesë tavoline", de:"Tischdecke", note:"Tosk: mbulesë tavoline", cat:"shtepi" },
  { id:160, gheg:"pecetë", de:"Serviette", note:"Tosk: pecetë", cat:"shtepi" },
  // ── MOBILJE (86 Wörter) ──
  { id:161, gheg:"enë / enët", de:"Geschirr", note:"Tosk: enë", cat:"mobilje" },
  { id:162, gheg:"pjatë / pjata", de:"Teller", note:"Tosk: pjatë", cat:"mobilje" },
  { id:163, gheg:"filxhan / filxhani", de:"Tasse", note:"[GHEG] Tosk: filxhan", cat:"mobilje" },
  { id:164, gheg:"gotë / gota", de:"Glas", note:"Tosk: gotë", cat:"mobilje" },
  { id:165, gheg:"shishe", de:"Flasche", note:"Tosk: shishe", cat:"mobilje" },
  { id:166, gheg:"thikë", de:"Messer", note:"Tosk: thikë", cat:"mobilje" },
  { id:167, gheg:"pirun", de:"Gabel", note:"Tosk: pirun", cat:"mobilje" },
  { id:168, gheg:"lugë", de:"Löffel", note:"Tosk: lugë", cat:"mobilje" },
  { id:169, gheg:"lugë çaji", de:"Teelöffel", note:"Tosk: lugë çaji", cat:"mobilje" },
  { id:170, gheg:"tenxhere", de:"Topf", note:"Tosk: tenxhere", cat:"mobilje" },
  { id:171, gheg:"tigan", de:"Pfanne", note:"Tosk: tigan", cat:"mobilje" },
  { id:172, gheg:"tavë", de:"Auflaufform / Backform", note:"Tosk: tavë", cat:"mobilje" },
  { id:173, gheg:"tepsi", de:"Backblech", note:"Tosk: tepsi (türk. Lehnwort, beide Dialekte)", cat:"mobilje" },
  { id:174, gheg:"sitë", de:"Sieb", note:"Tosk: sitë", cat:"mobilje" },
  { id:175, gheg:"kullesë", de:"Abtropfsieb / Küchensieb", note:"Tosk: kullesë", cat:"mobilje" },
  { id:176, gheg:"rendë", de:"Reibe", note:"Tosk: rendë", cat:"mobilje" },
  { id:177, gheg:"okllai", de:"Nudelholz", note:"[GHEG] Tosk: oklla", cat:"mobilje" },
  { id:178, gheg:"thyesë", de:"Nussknacker", note:"Tosk: thyesë arrash", cat:"mobilje" },
  { id:179, gheg:"çekiç", de:"Hammer", note:"Tosk: çekiç", cat:"mobilje" },
  { id:180, gheg:"gërshërë", de:"Schere", note:"Tosk: gërshërë", cat:"mobilje" },
  { id:181, gheg:"shiringë", de:"Spritze (auch Küchenspritze)", note:"Tosk: shiringë", cat:"mobilje" },
  { id:182, gheg:"makinë larëse", de:"Waschmaschine", note:"Tosk: makinë larëse", cat:"mobilje" },
  { id:183, gheg:"makinë enësh", de:"Spülmaschine", note:"Tosk: pjatalarëse", cat:"mobilje" },
  { id:184, gheg:"frigorifer / frigoriferi", de:"Kühlschrank", note:"Tosk: frigorifer", cat:"mobilje" },
  { id:185, gheg:"ngrirës", de:"Gefrierschrank", note:"Tosk: ngrirës", cat:"mobilje" },
  { id:186, gheg:"furrë / furra", de:"Ofen / Backofen", note:"Tosk: furrë", cat:"mobilje" },
  { id:187, gheg:"mikrovalë", de:"Mikrowelle", note:"Tosk: mikrovalë", cat:"mobilje" },
  { id:188, gheg:"bllender / blender", de:"Mixer", note:"Tosk: blender", cat:"mobilje" },
  { id:189, gheg:"makinë kafeje", de:"Kaffeemaschine", note:"Tosk: makinë kafeje", cat:"mobilje" },
  { id:190, gheg:"ibrik / ibriku", de:"Kaffeekännchen (türk.)", note:"[GHEG] Tosk: ibrik", cat:"mobilje" },
  { id:191, gheg:"çezme", de:"Wasserhahn (türk.)", note:"[GHEG] Tosk: rubinet", cat:"mobilje" },
  { id:192, gheg:"lavatrice", de:"Waschmaschine", note:"[GHEG] ital. Lehnwort; Tosk: lavatrice (gleich); Waschbecken = lavaman", cat:"mobilje" },
  { id:193, gheg:"kovë / kova", de:"Eimer", note:"Tosk: kovë", cat:"mobilje" },
  { id:194, gheg:"fshesë", de:"Besen", note:"Tosk: fshesë", cat:"mobilje" },
  { id:195, gheg:"fshesë me korrent", de:"Staubsauger", note:"Tosk: fshesë me korrent", cat:"mobilje" },
  { id:196, gheg:"leckë / lecka", de:"Lappen / Putztuch", note:"Tosk: leckë", cat:"mobilje" },
  { id:197, gheg:"sfungjer", de:"Schwamm", note:"Tosk: sfungjer", cat:"mobilje" },
  { id:198, gheg:"detergjent", de:"Waschmittel", note:"Tosk: detergjent", cat:"mobilje" },
  { id:199, gheg:"sapun", de:"Seife", note:"Tosk: sapun", cat:"mobilje" },
  { id:200, gheg:"shampo / shampua", de:"Shampoo", note:"Tosk: shampo", cat:"mobilje" },
  { id:201, gheg:"peshqir", de:"Handtuch", note:"Tosk: peshqir", cat:"mobilje" },
  { id:202, gheg:"letër higjienike", de:"Toilettenpapier", note:"Tosk: letër higjienike", cat:"mobilje" },
  { id:203, gheg:"mbështjellës ushqimi", de:"Frischhaltefolie", note:"Tosk: mbështjellës ushqimi", cat:"mobilje" },
  { id:204, gheg:"letër alumini", de:"Alufolie", note:"Tosk: letër alumini", cat:"mobilje" },
  { id:205, gheg:"plehra / plehrat", de:"Müll", note:"Tosk: plehra", cat:"mobilje" },
  { id:206, gheg:"qese plehrash", de:"Müllbeutel", note:"Tosk: qese plehrash", cat:"mobilje" },
  { id:207, gheg:"kosh i plehrave", de:"Mülleimer", note:"Tosk: kosh plehrash", cat:"mobilje" },
  { id:208, gheg:"shportë / shporta", de:"Korb", note:"Tosk: shportë", cat:"mobilje" },
  { id:209, gheg:"çantë / çanta", de:"Tasche", note:"Tosk: çantë", cat:"mobilje" },
  { id:210, gheg:"çantë pazar", de:"Einkaufstasche", note:"Tosk: çantë pazar", cat:"mobilje" },
  { id:211, gheg:"kuti / kutia", de:"Schachtel / Kiste", note:"Tosk: kuti", cat:"mobilje" },
  { id:212, gheg:"shkrepëse", de:"Streichholz", note:"Tosk: shkrepëse", cat:"mobilje" },
  { id:213, gheg:"qiri / qiriri", de:"Kerze", note:"Tosk: qiri", cat:"mobilje" },
  { id:214, gheg:"llambë", de:"Lampe / Leuchte", note:"Tosk: llambë", cat:"mobilje" },
  { id:215, gheg:"bateri / bateria", de:"Batterie", note:"Tosk: bateri", cat:"mobilje" },
  { id:216, gheg:"llambushkë", de:"Glühbirne", note:"[GHEG] Tosk: llambë", cat:"mobilje" },
  { id:217, gheg:"prizë", de:"Steckdose", note:"Tosk: prizë", cat:"mobilje" },
  { id:218, gheg:"kabëll", de:"Kabel", note:"Tosk: kabëll", cat:"mobilje" },
  { id:219, gheg:"mobilje", de:"Möbel", note:"Tosk: mobilje", cat:"mobilje" },
  { id:220, gheg:"karrige lëkundëse", de:"Schaukelstuhl", note:"Tosk: karrige lëkundëse; Wiege = djep; Trage = bartës", cat:"mobilje" },
  { id:221, gheg:"bank / banka", de:"Bank (Sitzbank)", note:"Tosk: bankë", cat:"mobilje" },
  { id:222, gheg:"stol", de:"Hocker", note:"Tosk: stol", cat:"mobilje" },
  { id:223, gheg:"rek / raku", de:"Regal", note:"[GHEG] Tosk: raft", cat:"mobilje" },
  { id:224, gheg:"raft", de:"Regal", note:"Tosk: raft", cat:"mobilje" },
  { id:225, gheg:"varëse", de:"Garderobe / Kleiderständer", note:"Tosk: varëse", cat:"mobilje" },
  { id:226, gheg:"kornizë", de:"Bilderrahmen", note:"Tosk: kornizë", cat:"mobilje" },
  { id:227, gheg:"fotografi", de:"Foto / Bild", note:"Tosk: fotografi", cat:"mobilje" },
  { id:228, gheg:"orë / ora", de:"Uhr", note:"Tosk: orë", cat:"mobilje" },
  { id:229, gheg:"orë muri", de:"Wanduhr", note:"Tosk: orë muri", cat:"mobilje" },
  { id:230, gheg:"ora me zile", de:"Wecker", note:"Tosk: orë me zile", cat:"mobilje" },
  { id:231, gheg:"kalendar", de:"Kalender", note:"Tosk: kalendar", cat:"mobilje" },
  { id:232, gheg:"telefon", de:"Telefon", note:"Tosk: telefon", cat:"mobilje" },
  { id:233, gheg:"televizor / TV", de:"Fernseher", note:"Tosk: televizor", cat:"mobilje" },
  { id:234, gheg:"kompjuter", de:"Computer", note:"Tosk: kompjuter", cat:"mobilje" },
  { id:235, gheg:"radio / radjo", de:"Radio", note:"Tosk: radio", cat:"mobilje" },
  { id:236, gheg:"telekomandë", de:"Fernbedienung", note:"Tosk: telekomandë; ACHTUNG: Künstliches Wort, kein echtes Gheg", cat:"mobilje" },
  { id:237, gheg:"libër / libri", de:"Buch", note:"Tosk: libër", cat:"mobilje" },
  { id:238, gheg:"revistë", de:"Zeitschrift", note:"Tosk: revistë", cat:"mobilje" },
  { id:239, gheg:"gazetë", de:"Zeitung", note:"Tosk: gazetë", cat:"mobilje" },
  { id:240, gheg:"letër / letra", de:"Papier / Brief", note:"Tosk: letër", cat:"mobilje" },
  { id:241, gheg:"stilograf", de:"Kugelschreiber", note:"Tosk: stilograf", cat:"mobilje" },
  { id:242, gheg:"laps / lapsi", de:"Bleistift", note:"Tosk: laps", cat:"mobilje" },
  { id:243, gheg:"gome / goma", de:"Radiergummi", note:"Tosk: gomë", cat:"mobilje" },
  { id:244, gheg:"vizore", de:"Lineal", note:"Tosk: vizore", cat:"mobilje" },
  { id:245, gheg:"zarf / zarfi", de:"Umschlag", note:"Tosk: zarf", cat:"mobilje" },
  { id:246, gheg:"çantë shkolle", de:"Schultasche / Rucksack", note:"Tosk: çantë shkolle", cat:"mobilje" },
  // ── USHQIM (219 Wörter) ──
  { id:247, gheg:"ushqim", de:"Essen / Nahrung", note:"Tosk: ushqim", cat:"ushqim" },
  { id:248, gheg:"bukë", de:"Brot", note:"Tosk: bukë", cat:"ushqim" },
  { id:249, gheg:"bukë misri", de:"Maisbrot", note:"Tosk: bukë misri", cat:"ushqim" },
  { id:250, gheg:"mish", de:"Fleisch", note:"Tosk: mish", cat:"ushqim" },
  { id:251, gheg:"mish lope", de:"Rindfleisch", note:"Tosk: mish lope", cat:"ushqim" },
  { id:252, gheg:"mish viçi", de:"Kalbfleisch", note:"Tosk: mish viçi", cat:"ushqim" },
  { id:253, gheg:"mish derri", de:"Schweinefleisch", note:"Tosk: mish derri", cat:"ushqim" },
  { id:254, gheg:"mish qengji", de:"Lammfleisch", note:"Tosk: mish qengji", cat:"ushqim" },
  { id:255, gheg:"mish pule", de:"Hühnerfleisch", note:"Tosk: mish pule", cat:"ushqim" },
  { id:256, gheg:"mish dhensh", de:"Hammelfleisch", note:"Tosk: mish dele", cat:"ushqim" },
  { id:257, gheg:"qofte", de:"Hackbällchen / Frikadellen", note:"Tosk: qofte", cat:"ushqim" },
  { id:258, gheg:"suxhuk", de:"Sucuk (türkische Knoblauchwurst)", note:"Tosk: suxhuk", cat:"ushqim" },
  { id:259, gheg:"proshutë", de:"Schinken", note:"Tosk: proshutë", cat:"ushqim" },
  { id:260, gheg:"sallam", de:"Wurst (allg.)", note:"Tosk: sallam", cat:"ushqim" },
  { id:261, gheg:"djathë", de:"Käse", note:"Tosk: djathë (gleich)", cat:"ushqim" },
  { id:262, gheg:"djathë i bardhë", de:"Weißkäse (Feta-ähnlich)", note:"Tosk: djathë i bardhë", cat:"ushqim" },
  { id:263, gheg:"djathë i verdhë", de:"Gelbkäse (Gouda-ähnlich)", note:"Tosk: djathë i verdhë", cat:"ushqim" },
  { id:264, gheg:"kos", de:"Joghurt", note:"Tosk: kos", cat:"ushqim" },
  { id:265, gheg:"kosi", de:"Sauermilch / Ayran", note:"[GHEG] Tosk: kos i lëngshëm", cat:"ushqim" },
  { id:266, gheg:"qumësht / qumështi", de:"Milch", note:"Tosk: qumësht", cat:"ushqim" },
  { id:267, gheg:"qumësht i thartë / kos", de:"Sauermilch", note:"[GHEG] Tosk: dhallë", cat:"ushqim" },
  { id:268, gheg:"dhallë", de:"Buttermilch", note:"Tosk: dhallë", cat:"ushqim" },
  { id:269, gheg:"ajkë", de:"Sahne / Rahm", note:"Tosk: ajkë", cat:"ushqim" },
  { id:270, gheg:"gjalpë", de:"Butter", note:"Tosk: gjalpë (gleich)", cat:"ushqim" },
  { id:271, gheg:"vaj", de:"Öl", note:"Tosk: vaj", cat:"ushqim" },
  { id:272, gheg:"vaj ulliri", de:"Olivenöl", note:"Tosk: vaj ulliri", cat:"ushqim" },
  { id:273, gheg:"vaj luledielli", de:"Sonnenblumenöl", note:"Tosk: vaj luledielli", cat:"ushqim" },
  { id:274, gheg:"uthull", de:"Essig", note:"Tosk: uthull", cat:"ushqim" },
  { id:275, gheg:"kripë", de:"Salz", note:"Tosk: kripë", cat:"ushqim" },
  { id:276, gheg:"piper", de:"Pfeffer", note:"Tosk: piper", cat:"ushqim" },
  { id:277, gheg:"spec / speci", de:"Paprika (Gewürz)", note:"Tosk: spec", cat:"ushqim" },
  { id:278, gheg:"erëza", de:"Gewürze", note:"Tosk: erëza", cat:"ushqim" },
  { id:279, gheg:"majat / majaja", de:"Hefe", note:"Tosk: maja", cat:"ushqim" },
  { id:280, gheg:"sheqer", de:"Zucker", note:"Tosk: sheqer", cat:"ushqim" },
  { id:281, gheg:"mjaltë / mjalti", de:"Honig", note:"Tosk: mjaltë (gleich)", cat:"ushqim" },
  { id:282, gheg:"reçel", de:"Marmelade", note:"Tosk: reçel", cat:"ushqim" },
  { id:283, gheg:"çokollatë", de:"Schokolade", note:"Tosk: çokollatë", cat:"ushqim" },
  { id:284, gheg:"kaka / kakao", de:"Kakao", note:"[GHEG] Tosk: kakao", cat:"ushqim" },
  { id:285, gheg:"miell", de:"Mehl", note:"Tosk: miell", cat:"ushqim" },
  { id:286, gheg:"oriz", de:"Reis", note:"Tosk: oriz", cat:"ushqim" },
  { id:287, gheg:"makarona", de:"Nudeln (allg.)", note:"Tosk: makarona", cat:"ushqim" },
  { id:288, gheg:"vezë / veza", de:"Ei", note:"Tosk: vezë", cat:"ushqim" },
  { id:289, gheg:"vezë të ziera", de:"gekochte Eier", note:"Tosk: vezë të ziera", cat:"ushqim" },
  { id:290, gheg:"vezë të skuqura", de:"Spiegeleier", note:"Tosk: vezë të skuqura", cat:"ushqim" },
  { id:291, gheg:"thërrime / thërrimet", de:"Semmelbrösel", note:"Tosk: thërrime", cat:"ushqim" },
  { id:292, gheg:"brum / brumi", de:"Teig", note:"[GHEG] Tosk: brumë", cat:"ushqim" },
  { id:293, gheg:"pastë / pasta", de:"Nudel-/Blätterteig", note:"Tosk: pastë", cat:"ushqim" },
  { id:294, gheg:"salcë", de:"Soße", note:"Tosk: salcë", cat:"ushqim" },
  { id:295, gheg:"supë", de:"Suppe", note:"Tosk: supë", cat:"ushqim" },
  { id:296, gheg:"lëng / lëngu", de:"Saft / Brühe", note:"Tosk: lëng", cat:"ushqim" },
  { id:297, gheg:"fruta / frutat", de:"Obst (allg.)", note:"Tosk: fruta", cat:"ushqim" },
  { id:298, gheg:"pemë", de:"Obst (Bäume)", note:"Tosk: pemë", cat:"ushqim" },
  { id:299, gheg:"mollë", de:"Apfel", note:"Tosk: mollë", cat:"ushqim" },
  { id:300, gheg:"dardhë", de:"Birne", note:"Tosk: dardhë", cat:"ushqim" },
  { id:301, gheg:"kumbull / kumbulla", de:"Pflaume", note:"Tosk: kumbull", cat:"ushqim" },
  { id:302, gheg:"qershi", de:"Kirsche", note:"Tosk: qershi", cat:"ushqim" },
  { id:303, gheg:"vishnjë", de:"Sauerkirsche", note:"Tosk: vishnjë", cat:"ushqim" },
  { id:304, gheg:"pjeshkë", de:"Pfirsich", note:"Tosk: pjeshkë", cat:"ushqim" },
  { id:305, gheg:"kajsi / kajsia", de:"Aprikose", note:"Tosk: kajsi", cat:"ushqim" },
  { id:306, gheg:"rrush / rrushi", de:"Weintrauben", note:"Tosk: rrush", cat:"ushqim" },
  { id:307, gheg:"luleshtrydhe", de:"Erdbeere", note:"Tosk: luleshtrydhe", cat:"ushqim" },
  { id:308, gheg:"mjedër / mjedra", de:"Himbeere", note:"Tosk: mjedër", cat:"ushqim" },
  { id:309, gheg:"boronicë", de:"Blaubeere / Heidelbeere", note:"Tosk: boronicë", cat:"ushqim" },
  { id:310, gheg:"mani / mania", de:"Maulbeere", note:"Tosk: mani", cat:"ushqim" },
  { id:311, gheg:"fik / fiku", de:"Feige", note:"Tosk: fik", cat:"ushqim" },
  { id:312, gheg:"limon", de:"Zitrone", note:"Tosk: limon", cat:"ushqim" },
  { id:313, gheg:"portokall", de:"Orange / Apfelsine", note:"Tosk: portokall", cat:"ushqim" },
  { id:314, gheg:"mandarinë", de:"Mandarine", note:"Tosk: mandarinë", cat:"ushqim" },
  { id:315, gheg:"grejpfrut", de:"Grapefruit", note:"Tosk: grejpfrut", cat:"ushqim" },
  { id:316, gheg:"bananë", de:"Banane", note:"Tosk: bananë", cat:"ushqim" },
  { id:317, gheg:"ananás / ananas", de:"Ananas", note:"Tosk: ananas", cat:"ushqim" },
  { id:318, gheg:"shalqi / shalqiri", de:"Wassermelone", note:"[GHEG] Tosk: shalqi", cat:"ushqim" },
  { id:319, gheg:"piepër / piepri", de:"Melone / Honigmelone", note:"[GHEG] Tosk: pjepër", cat:"ushqim" },
  { id:320, gheg:"hurma / hurmë", de:"Dattel / Kaki", note:"Tosk: hurmë", cat:"ushqim" },
  { id:321, gheg:"arrë / arra", de:"Walnuss", note:"Tosk: arrë", cat:"ushqim" },
  { id:322, gheg:"lajthi / lajthia", de:"Haselnuss", note:"Tosk: lajthi", cat:"ushqim" },
  { id:323, gheg:"bajame", de:"Mandel", note:"Tosk: bajame", cat:"ushqim" },
  { id:324, gheg:"kikirik", de:"Erdnuss", note:"Tosk: kikirikë", cat:"ushqim" },
  { id:325, gheg:"fëstëk / fëstëku", de:"Pistazie", note:"Tosk: fëstëk", cat:"ushqim" },
  { id:326, gheg:"gështenjë", de:"Kastanie / Marone", note:"Tosk: gështenjë", cat:"ushqim" },
  { id:327, gheg:"ulli / ulliri", de:"Olive", note:"Tosk: ulli", cat:"ushqim" },
  { id:328, gheg:"mollë e egër", de:"Holzapfel", note:"Tosk: mollë e egër", cat:"ushqim" },
  { id:329, gheg:"thanë / thana", de:"Kornelkirsche", note:"[GHEG] Tosk: thanë", cat:"ushqim" },
  { id:330, gheg:"perime", de:"Gemüse", note:"Tosk: perime", cat:"ushqim" },
  { id:331, gheg:"domate / domatet", de:"Tomaten", note:"Tosk: domate", cat:"ushqim" },
  { id:332, gheg:"tranguj / trangujt", de:"Gurken", note:"[GHEG] Tosk: kastravec", cat:"ushqim" },
  { id:333, gheg:"kastravec", de:"Gurke", note:"Tosk: kastravec", cat:"ushqim" },
  { id:334, gheg:"speca", de:"Paprika (Schoten)", note:"Tosk: speca", cat:"ushqim" },
  { id:335, gheg:"speca djegës", de:"scharfe Paprika / Chili", note:"Tosk: speca djegës", cat:"ushqim" },
  { id:336, gheg:"qepë / qepa", de:"Zwiebel", note:"Tosk: qepë", cat:"ushqim" },
  { id:337, gheg:"hudhër / hudhra", de:"Knoblauch", note:"Tosk: hudhër", cat:"ushqim" },
  { id:338, gheg:"presh / preshi", de:"Lauch / Porree", note:"Tosk: presh", cat:"ushqim" },
  { id:339, gheg:"karotë / karota", de:"Karotte / Möhre", note:"Tosk: karotë", cat:"ushqim" },
  { id:340, gheg:"patate / patatet", de:"Kartoffeln", note:"Tosk: patate", cat:"ushqim" },
  { id:341, gheg:"patate të skuqura", de:"Pommes frites", note:"Tosk: patate të skuqura", cat:"ushqim" },
  { id:342, gheg:"lulelakër", de:"Blumenkohl", note:"Tosk: lulelakër", cat:"ushqim" },
  { id:343, gheg:"lakër / lakra", de:"Kohl", note:"Tosk: lakër", cat:"ushqim" },
  { id:344, gheg:"lakër turshi", de:"Sauerkraut", note:"Tosk: lakër turshi", cat:"ushqim" },
  { id:345, gheg:"spinaq", de:"Spinat", note:"Tosk: spinaq", cat:"ushqim" },
  { id:346, gheg:"sallatë", de:"Salat (grün)", note:"Tosk: sallatë", cat:"ushqim" },
  { id:347, gheg:"marule", de:"Kopfsalat", note:"Tosk: marule", cat:"ushqim" },
  { id:348, gheg:"majdanoz", de:"Petersilie", note:"Tosk: majdanoz", cat:"ushqim" },
  { id:349, gheg:"selino", de:"Sellerie", note:"Tosk: selino", cat:"ushqim" },
  { id:350, gheg:"kopër", de:"Dill", note:"Tosk: kopër", cat:"ushqim" },
  { id:351, gheg:"borzilok", de:"Basilikum", note:"Tosk: borzilok", cat:"ushqim" },
  { id:352, gheg:"nenexhik / mente", de:"Minze", note:"[GHEG] Tosk: mente", cat:"ushqim" },
  { id:353, gheg:"rigon", de:"Oregano", note:"Tosk: rigon", cat:"ushqim" },
  { id:354, gheg:"piper i zi", de:"schwarzer Pfeffer", note:"Tosk: piper i zi", cat:"ushqim" },
  { id:355, gheg:"piper i kuq", de:"roter Pfeffer / Paprika", note:"Tosk: piper i kuq", cat:"ushqim" },
  { id:356, gheg:"shafran / shafrani", de:"Safran", note:"Tosk: shafran", cat:"ushqim" },
  { id:357, gheg:"kërpudhë", de:"Pilz", note:"Tosk: kërpudhë", cat:"ushqim" },
  { id:358, gheg:"fasule / fasulet", de:"Bohnen", note:"Tosk: fasule", cat:"ushqim" },
  { id:359, gheg:"thjerrëza", de:"Linsen", note:"Tosk: thjerrëza", cat:"ushqim" },
  { id:360, gheg:"bizele", de:"Erbsen", note:"Tosk: bizele", cat:"ushqim" },
  { id:361, gheg:"misër / misri", de:"Mais", note:"Tosk: misër", cat:"ushqim" },
  { id:362, gheg:"oriz", de:"Reis", note:"Tosk: oriz", cat:"ushqim" },
  { id:363, gheg:"grurë / gruri", de:"Weizen", note:"Tosk: grurë", cat:"ushqim" },
  { id:364, gheg:"ther / thekra", de:"Roggen", note:"[GHEG] Tosk: thekër", cat:"ushqim" },
  { id:365, gheg:"tërshërë", de:"Hafer", note:"Tosk: tërshërë", cat:"ushqim" },
  { id:366, gheg:"patëllxhan", de:"Aubergine", note:"Tosk: patëllxhan", cat:"ushqim" },
  { id:367, gheg:"kungull / kungulli", de:"Kürbis", note:"Tosk: kungull", cat:"ushqim" },
  { id:368, gheg:"kungull i njomë", de:"Zucchini", note:"Tosk: kungull i njomë", cat:"ushqim" },
  { id:369, gheg:"panxhar / panxhari", de:"Rote Bete", note:"Tosk: panxhar", cat:"ushqim" },
  { id:370, gheg:"rrepë / rrepa", de:"Rübe", note:"Tosk: rrepë", cat:"ushqim" },
  { id:371, gheg:"rrepkë", de:"Radieschen", note:"Tosk: rrepkë", cat:"ushqim" },
  { id:372, gheg:"angjinare", de:"Artischocke", note:"Tosk: angjinare", cat:"ushqim" },
  { id:373, gheg:"ullinj / ullinjtë", de:"Oliven", note:"Tosk: ullinj", cat:"ushqim" },
  { id:374, gheg:"turshi", de:"eingelegtes Gemüse", note:"Tosk: turshi", cat:"ushqim" },
  { id:375, gheg:"pije", de:"Getränk", note:"Tosk: pije", cat:"ushqim" },
  { id:376, gheg:"ujë / uji", de:"Wasser", note:"Tosk: ujë", cat:"ushqim" },
  { id:377, gheg:"ujë i gazuar", de:"Sprudelwasser", note:"Tosk: ujë i gazuar", cat:"ushqim" },
  { id:378, gheg:"ujë mineral", de:"Mineralwasser", note:"Tosk: ujë mineral", cat:"ushqim" },
  { id:379, gheg:"kafe / kafja", de:"Kaffee", note:"Tosk: kafe", cat:"ushqim" },
  { id:380, gheg:"kafe turke", de:"türkischer Kaffee", note:"Tosk: kafe turke", cat:"ushqim" },
  { id:381, gheg:"kafe me qumësht", de:"Milchkaffee", note:"Tosk: kafe me qumësht", cat:"ushqim" },
  { id:382, gheg:"kafe e zezë", de:"schwarzer Kaffee", note:"Tosk: kafe e zezë", cat:"ushqim" },
  { id:383, gheg:"çaj / çaji", de:"Tee", note:"Tosk: çaj", cat:"ushqim" },
  { id:384, gheg:"çaj mali", de:"Bergtee (Kosovo-Kräutertee)", note:"Tosk: çaj mali", cat:"ushqim" },
  { id:385, gheg:"çaj bliri", de:"Lindenblütentee", note:"Tosk: çaj bliri", cat:"ushqim" },
  { id:386, gheg:"çaj kamomili", de:"Kamillentee", note:"Tosk: çaj kamomili", cat:"ushqim" },
  { id:387, gheg:"lëng portokalli", de:"Orangensaft", note:"Tosk: lëng portokalli", cat:"ushqim" },
  { id:388, gheg:"limonatë", de:"Limonade / Zitronensaft", note:"Tosk: limonatë", cat:"ushqim" },
  { id:389, gheg:"qumësht", de:"Milch", note:"Tosk: qumësht", cat:"ushqim" },
  { id:390, gheg:"kakao", de:"Kakao", note:"Tosk: kakao", cat:"ushqim" },
  { id:391, gheg:"bozë / boza", de:"Boza (Hirse-Getränk)", note:"Tosk: bozë", cat:"ushqim" },
  { id:392, gheg:"ajran", de:"Ayran (Joghurtgetränk)", note:"Tosk: dhallë / ajran", cat:"ushqim" },
  { id:393, gheg:"birrë / birra", de:"Bier", note:"Tosk: birrë", cat:"ushqim" },
  { id:394, gheg:"birrë pa alkool", de:"alkoholfreies Bier", note:"Tosk: birrë pa alkool", cat:"ushqim" },
  { id:395, gheg:"verë / vera", de:"Wein", note:"Tosk: verë", cat:"ushqim" },
  { id:396, gheg:"verë e bardhë", de:"Weißwein", note:"Tosk: verë e bardhë", cat:"ushqim" },
  { id:397, gheg:"verë e kuqe", de:"Rotwein", note:"Tosk: verë e kuqe", cat:"ushqim" },
  { id:398, gheg:"rakí / rakija", de:"Raki (Schnaps, oft Traube)", note:"[GHEG] Tosk: raki", cat:"ushqim" },
  { id:399, gheg:"konjak", de:"Cognac", note:"Tosk: konjak", cat:"ushqim" },
  { id:400, gheg:"liker / likeri", de:"Likör", note:"Tosk: liker", cat:"ushqim" },
  { id:401, gheg:"shurup / shurupi", de:"Sirup", note:"Tosk: shurup", cat:"ushqim" },
  { id:402, gheg:"lëng frutash", de:"Fruchtsaft", note:"Tosk: lëng frutash", cat:"ushqim" },
  { id:403, gheg:"qumsht / qumshti", de:"Milch (Gheg-Aussprache)", note:"[GHEG] Tosk: qumësht; Nasal-vokal", cat:"ushqim" },
  { id:404, gheg:"dik", de:"Milch (dialektal, Kinderwort)", note:"[GHEG] regional", cat:"ushqim" },
  { id:405, gheg:"vakt / vakti", de:"Mahlzeit", note:"Tosk: vakt", cat:"ushqim" },
  { id:406, gheg:"mëngjes", de:"Frühstück", note:"Tosk: mëngjes", cat:"ushqim" },
  { id:407, gheg:"drekë / dreka", de:"Mittagessen", note:"Tosk: drekë", cat:"ushqim" },
  { id:408, gheg:"darkë / darka", de:"Abendessen", note:"Tosk: darkë", cat:"ushqim" },
  { id:409, gheg:"ushqim i lehtë", de:"Snack / kleine Mahlzeit", note:"Tosk: ushqim i lehtë", cat:"ushqim" },
  { id:410, gheg:"meze", de:"Vorspeise / Meze", note:"Tosk: meze", cat:"ushqim" },
  { id:411, gheg:"ëmbëlsirë", de:"Nachspeise / Dessert", note:"Tosk: ëmbëlsirë", cat:"ushqim" },
  { id:412, gheg:"gatuaj", de:"kochen (Verb)", note:"Tosk: gatuaj", cat:"ushqim" },
  { id:413, gheg:"ziej", de:"kochen / sieden", note:"Tosk: ziej", cat:"ushqim" },
  { id:414, gheg:"ziej në zjarr të ulët", de:"köcheln lassen", note:"Tosk: ziej në zjarr të ulët", cat:"ushqim" },
  { id:415, gheg:"skuq", de:"braten", note:"Tosk: skuq", cat:"ushqim" },
  { id:416, gheg:"piek / pjek", de:"backen / braten (Ofen)", note:"[GHEG] Tosk: pjek", cat:"ushqim" },
  { id:417, gheg:"pjek në furrë", de:"im Ofen backen", note:"Tosk: pjek në furrë", cat:"ushqim" },
  { id:418, gheg:"pjek në tigan", de:"in der Pfanne braten", note:"Tosk: pjek në tigan", cat:"ushqim" },
  { id:419, gheg:"ziej në avull", de:"dämpfen", note:"Tosk: ziej në avull", cat:"ushqim" },
  { id:420, gheg:"përvëloj", de:"blanchieren", note:"Tosk: përvëloj", cat:"ushqim" },
  { id:421, gheg:"ngrij / ngrirë", de:"einfrieren", note:"Tosk: ngrij", cat:"ushqim" },
  { id:422, gheg:"shkrij", de:"schmelzen / auftauen", note:"Tosk: shkrij", cat:"ushqim" },
  { id:423, gheg:"shkrij në frigorifer", de:"im Kühlschrank auftauen", note:"Tosk: shkrij në frigorifer", cat:"ushqim" },
  { id:424, gheg:"pres / presë", de:"schneiden", note:"[GHEG] Tosk: pres", cat:"ushqim" },
  { id:425, gheg:"qëroj", de:"schälen", note:"Tosk: qëroj", cat:"ushqim" },
  { id:426, gheg:"grar / grij", de:"reiben / hacken", note:"[GHEG] Tosk: grij", cat:"ushqim" },
  { id:427, gheg:"përziej", de:"mischen / umrühren", note:"Tosk: përziej", cat:"ushqim" },
  { id:428, gheg:"hedh / hedhë", de:"werfen / hinzufügen", note:"[GHEG] Tosk: hedh", cat:"ushqim" },
  { id:429, gheg:"shtoj", de:"hinzufügen", note:"Tosk: shtoj", cat:"ushqim" },
  { id:430, gheg:"shijoj", de:"abschmecken", note:"Tosk: shijoj", cat:"ushqim" },
  { id:431, gheg:"shijshëm", de:"lecker", note:"Tosk: i shijshëm", cat:"ushqim" },
  { id:432, gheg:"e shijshme", de:"lecker (f.)", note:"Tosk: e shijshme", cat:"ushqim" },
  { id:433, gheg:"ngrënë / ha", de:"essen", note:"[GHEG] Tosk: ha", cat:"ushqim" },
  { id:434, gheg:"ha mirë", de:"gut essen / genießen", note:"Tosk: ha mirë", cat:"ushqim" },
  { id:435, gheg:"pi", de:"trinken", note:"Tosk: pi", cat:"ushqim" },
  { id:436, gheg:"ngrënia", de:"das Essen (Substantiv)", note:"Tosk: ngrënia", cat:"ushqim" },
  { id:437, gheg:"të pi", de:"trinken (Substantiv)", note:"Tosk: të pirë", cat:"ushqim" },
  { id:438, gheg:"përgatit", de:"zubereiten", note:"Tosk: përgatit", cat:"ushqim" },
  { id:439, gheg:"përgatitje", de:"Zubereitung", note:"Tosk: përgatitje", cat:"ushqim" },
  { id:440, gheg:"recetë", de:"Rezept", note:"Tosk: recetë", cat:"ushqim" },
  { id:441, gheg:"përbërës", de:"Zutaten", note:"Tosk: përbërës", cat:"ushqim" },
  { id:442, gheg:"i uritur / e uritur", de:"hungrig", note:"Tosk: i uritur", cat:"ushqim" },
  { id:443, gheg:"kam uri", de:"ich habe Hunger", note:"Tosk: kam uri", cat:"ushqim" },
  { id:444, gheg:"i etshëm / e etshme", de:"durstig", note:"Tosk: i etur", cat:"ushqim" },
  { id:445, gheg:"kam etje", de:"ich habe Durst", note:"Tosk: kam etje", cat:"ushqim" },
  { id:446, gheg:"boll / mjaft", de:"genug", note:"[GHEG] Tosk: mjaft", cat:"ushqim" },
  { id:447, gheg:"qull / qulli", de:"Brei / Matsch", note:"Tosk: qull", cat:"ushqim" },
  { id:448, gheg:"fli / flija", de:"Flia (geschichteter Pfannkuchen)", note:"[GHEG] traditionelles Gericht Kosovos", cat:"ushqim" },
  { id:449, gheg:"pite / pita", de:"Pita (gefülltes Gebäck)", note:"Tosk: byrek / pite", cat:"ushqim" },
  { id:450, gheg:"byrek", de:"Börek (gefülltes Blätterteiggebäck)", note:"Tosk: byrek", cat:"ushqim" },
  { id:451, gheg:"bakllavë", de:"Baklava", note:"Tosk: bakllavë", cat:"ushqim" },
  { id:452, gheg:"hallvë / hallva", de:"Halva (Süßspeise)", note:"Tosk: hallvë", cat:"ushqim" },
  { id:453, gheg:"petulla", de:"Pfannkuchen (Krapfen)", note:"Tosk: petulla", cat:"ushqim" },
  { id:454, gheg:"pallë / palla", de:"Schwert / Mais-Pfannkuchen (regional)", note:"[GHEG] Bedeutung 'Schwert' (archaisch); regional auch Maisspeise", cat:"ushqim" },
  { id:455, gheg:"burek", de:"Fleischstrudel", note:"Tosk: byrek me mish", cat:"ushqim" },
  { id:456, gheg:"qebap", de:"Cevapcici / Hackfleischröllchen", note:"Tosk: qebap", cat:"ushqim" },
  { id:457, gheg:"qebapa", de:"gegrillte Hackfleischröllchen (Pl.)", note:"Tosk: qebapa", cat:"ushqim" },
  { id:458, gheg:"raki", de:"Raki (Obstbrand)", note:"Tosk: raki", cat:"ushqim" },
  { id:459, gheg:"salcë domatesh", de:"Tomatensauce", note:"Tosk: salcë domatesh", cat:"ushqim" },
  { id:460, gheg:"salcë kosi", de:"Joghurtsauce", note:"Tosk: salcë kosi", cat:"ushqim" },
  { id:461, gheg:"mish i pjekur", de:"Braten", note:"Tosk: mish i pjekur", cat:"ushqim" },
  { id:462, gheg:"mish i zier", de:"gekochtes Fleisch / Eintopf", note:"Tosk: mish i zier", cat:"ushqim" },
  { id:463, gheg:"tavë elbasani", de:"Elbasaner Auflauf", note:"Tosk: tavë elbasani", cat:"ushqim" },
  { id:464, gheg:"sallatë", de:"Salat", note:"Tosk: sallatë", cat:"ushqim" },
  { id:465, gheg:"sallatë shope", de:"Schop-Salat (Tomaten-Gurken-Zwiebeln)", note:"[GHEG] Kosova-Spezialität", cat:"ushqim" },
  // ── RROBA (77 Wörter) ──
  { id:466, gheg:"rroba / rrobat", de:"Kleidung", note:"[GHEG] Tosk: rroba / veshje", cat:"rroba" },
  { id:467, gheg:"veshje", de:"Kleidung (formell)", note:"Tosk: veshje", cat:"rroba" },
  { id:468, gheg:"këmishë", de:"Hemd", note:"Tosk: këmishë", cat:"rroba" },
  { id:469, gheg:"bluzë", de:"Bluse / T-Shirt", note:"Tosk: bluzë", cat:"rroba" },
  { id:470, gheg:"fanellë", de:"T-Shirt / Unterhemd", note:"[GHEG] Tosk: bluzë / fanellë", cat:"rroba" },
  { id:471, gheg:"t-shirt / T-shirt", de:"T-Shirt", note:"Tosk: bluzë", cat:"rroba" },
  { id:472, gheg:"këmishë sportive", de:"Polohemd", note:"Tosk: këmishë sportive", cat:"rroba" },
  { id:473, gheg:"pantallona", de:"Hose", note:"Tosk: pantallona", cat:"rroba" },
  { id:474, gheg:"pantallona xhins", de:"Jeans", note:"Tosk: pantallona xhins", cat:"rroba" },
  { id:475, gheg:"pantallona sportive", de:"Sporthose", note:"Tosk: pantallona sportive", cat:"rroba" },
  { id:476, gheg:"pantallona të shkurtra", de:"kurze Hose", note:"Tosk: pantallona të shkurtra", cat:"rroba" },
  { id:477, gheg:"brekë / brekët", de:"Unterhose", note:"Tosk: brekë", cat:"rroba" },
  { id:478, gheg:"të mbathura", de:"Unterwäsche (allg.)", note:"Tosk: të mbathura", cat:"rroba" },
  { id:479, gheg:"tirë / tira", de:"Unterhemd (ärmellos)", note:"[GHEG] Tosk: bluzë pa mëngë", cat:"rroba" },
  { id:480, gheg:"sutjena", de:"BH", note:"Tosk: sutjena", cat:"rroba" },
  { id:481, gheg:"çorape", de:"Socken", note:"Tosk: çorape", cat:"rroba" },
  { id:482, gheg:"geta", de:"Strumpfhose", note:"Tosk: geta", cat:"rroba" },
  { id:483, gheg:"fund / fundi", de:"Rock", note:"Tosk: fund", cat:"rroba" },
  { id:484, gheg:"fustan", de:"Kleid", note:"Tosk: fustan", cat:"rroba" },
  { id:485, gheg:"kostum / kostumi", de:"Anzug", note:"Tosk: kostum", cat:"rroba" },
  { id:486, gheg:"xhaketë", de:"Jacke", note:"Tosk: xhaketë", cat:"rroba" },
  { id:487, gheg:"pallto", de:"Mantel", note:"Tosk: pallto", cat:"rroba" },
  { id:488, gheg:"trençkë", de:"Trenchcoat", note:"Tosk: trençkë", cat:"rroba" },
  { id:489, gheg:"xhaketë lëkure", de:"Lederjacke", note:"Tosk: xhaketë lëkure", cat:"rroba" },
  { id:490, gheg:"trikotazh", de:"Strickjacke", note:"Tosk: trikotazh", cat:"rroba" },
  { id:491, gheg:"bluzë leshi", de:"Wollpullover", note:"Tosk: bluzë leshi", cat:"rroba" },
  { id:492, gheg:"kapuç / kapuçi", de:"Kapuze", note:"Tosk: kapuç", cat:"rroba" },
  { id:493, gheg:"kapuçinë", de:"Kapuzenjacke", note:"Tosk: xhaketë me kapuç", cat:"rroba" },
  { id:494, gheg:"jelek", de:"Weste", note:"Tosk: jelek", cat:"rroba" },
  { id:495, gheg:"këpucë / këpucët", de:"Schuhe", note:"Tosk: këpucë", cat:"rroba" },
  { id:496, gheg:"athlete / atlete", de:"Turnschuhe", note:"Tosk: atlete", cat:"rroba" },
  { id:497, gheg:"këpucë lëkure", de:"Lederschuhe", note:"Tosk: këpucë lëkure", cat:"rroba" },
  { id:498, gheg:"çizme", de:"Stiefel", note:"Tosk: çizme", cat:"rroba" },
  { id:499, gheg:"sandale", de:"Sandalen", note:"Tosk: sandale", cat:"rroba" },
  { id:500, gheg:"pantofla", de:"Hausschuhe / Pantoffeln", note:"Tosk: pantofla", cat:"rroba" },
  { id:501, gheg:"taka / taka të larta", de:"High Heels / Absätze", note:"Tosk: takë të larta", cat:"rroba" },
  { id:502, gheg:"lidhëse këpucësh", de:"Schnürsenkel", note:"Tosk: lidhëse këpucësh", cat:"rroba" },
  { id:503, gheg:"kapele / kapela", de:"Hut / Mütze", note:"Tosk: kapelë", cat:"rroba" },
  { id:504, gheg:"shami / shamia", de:"Tuch / Kopftuch", note:"Tosk: shami", cat:"rroba" },
  { id:505, gheg:"shall / shalli", de:"Schal", note:"Tosk: shall", cat:"rroba" },
  { id:506, gheg:"dorashka", de:"Handschuhe", note:"Tosk: dorashka", cat:"rroba" },
  { id:507, gheg:"rrip / rripi", de:"Gürtel", note:"Tosk: rrip", cat:"rroba" },
  { id:508, gheg:"rrip ore", de:"Uhrenarmband (wörtl. 'Uhrriemen')", note:"NICHT Armbanduhr! Armbanduhr = orë dore (siehe #509)", cat:"rroba" },
  { id:509, gheg:"orë dore", de:"Armbanduhr", note:"Tosk: orë dore", cat:"rroba" },
  { id:510, gheg:"syze", de:"Brille", note:"Tosk: syze", cat:"rroba" },
  { id:511, gheg:"syze dielli", de:"Sonnenbrille", note:"Tosk: syze dielli", cat:"rroba" },
  { id:512, gheg:"qantë / çanta", de:"Tasche", note:"Tosk: çantë", cat:"rroba" },
  { id:513, gheg:"çantë dore", de:"Handtasche", note:"Tosk: çantë dore", cat:"rroba" },
  { id:514, gheg:"kuletë / kuleta", de:"Geldbörse", note:"Tosk: kuletë (gleich)", cat:"rroba" },
  { id:515, gheg:"portofol", de:"Portemonnaie", note:"Tosk: portofol", cat:"rroba" },
  { id:516, gheg:"unazë", de:"Ring", note:"Tosk: unazë", cat:"rroba" },
  { id:517, gheg:"vathë / vathët", de:"Ohrringe", note:"Tosk: vathë", cat:"rroba" },
  { id:518, gheg:"gjerdan", de:"Halskette", note:"Tosk: gjerdan", cat:"rroba" },
  { id:519, gheg:"byzylyk", de:"Armband", note:"Tosk: byzylyk", cat:"rroba" },
  { id:520, gheg:"karficë", de:"Brosche / Anstecker", note:"Tosk: karficë", cat:"rroba" },
  { id:521, gheg:"gjamadan", de:"traditionelle Gheg-Weste (bestickt)", note:"[GHEG] traditionelle Tracht", cat:"rroba" },
  { id:522, gheg:"plis / plisi", de:"traditioneller Filzhut (Gheg)", note:"[GHEG] Tosk: plis", cat:"rroba" },
  { id:523, gheg:"qeleshe", de:"traditionelle weiße Filzkappe", note:"Tosk: qeleshe (gleich)", cat:"rroba" },
  { id:524, gheg:"knjall / knjalli", de:"Gürtel/Tasche (regional)", note:"[GHEG] regional Kosovo", cat:"rroba" },
  { id:525, gheg:"shportë", de:"Korb / Tasche aus Weide", note:"Tosk: shportë", cat:"rroba" },
  { id:526, gheg:"kopsa / kopsë", de:"Knopf", note:"Tosk: kopsë", cat:"rroba" },
  { id:527, gheg:"zigom / zinxhir", de:"Reißverschluss", note:"[GHEG] Tosk: zinxhir", cat:"rroba" },
  { id:528, gheg:"buton / butoni", de:"Knopf (regional)", note:"[GHEG] Tosk: kopsë", cat:"rroba" },
  { id:529, gheg:"veshëse", de:"Kleiderbügel", note:"Tosk: varëse rrobash", cat:"rroba" },
  { id:530, gheg:"hekur / hekuri", de:"Bügeleisen", note:"Tosk: hekur", cat:"rroba" },
  { id:531, gheg:"dërrasë hekurosjeje", de:"Bügelbrett", note:"Tosk: dërrasë hekurosjeje", cat:"rroba" },
  { id:532, gheg:"larje / larja", de:"Wäsche (Waschen)", note:"Tosk: larje", cat:"rroba" },
  { id:533, gheg:"laj", de:"waschen (Verb)", note:"Tosk: laj", cat:"rroba" },
  { id:534, gheg:"pastrim kimik", de:"chemische Reinigung", note:"Tosk: pastrim kimik", cat:"rroba" },
  { id:535, gheg:"rrobaqepës", de:"Schneider", note:"Tosk: rrobaqepës", cat:"rroba" },
  { id:536, gheg:"gjilpërë", de:"Nadel", note:"Tosk: gjilpërë", cat:"rroba" },
  { id:537, gheg:"pe / peri", de:"Faden", note:"Tosk: pe", cat:"rroba" },
  { id:538, gheg:"masë / masa", de:"Maßband / Maß", note:"Tosk: masë", cat:"rroba" },
  { id:539, gheg:"vesh / veshë", de:"anziehen", note:"[GHEG] Tosk: vesh", cat:"rroba" },
  { id:540, gheg:"vishem", de:"sich anziehen", note:"Tosk: vishem", cat:"rroba" },
  { id:541, gheg:"zhvishem", de:"sich ausziehen", note:"Tosk: zhvishem", cat:"rroba" },
  { id:542, gheg:"ndërroj rrobat", de:"Kleidung wechseln", note:"Tosk: ndërroj rrobat", cat:"rroba" },
  // ── TRUPI (124 Wörter) ──
  { id:543, gheg:"trup / trupi", de:"Körper", note:"Tosk: trup", cat:"trupi" },
  { id:544, gheg:"kokë / koka", de:"Kopf", note:"Tosk: kokë", cat:"trupi" },
  { id:545, gheg:"flokë / flokët", de:"Haare", note:"Tosk: flokë", cat:"trupi" },
  { id:546, gheg:"ballë / balli", de:"Stirn", note:"Tosk: ballë", cat:"trupi" },
  { id:547, gheg:"sy / sytë", de:"Auge / Augen", note:"Tosk: sy", cat:"trupi" },
  { id:548, gheg:"vetull / vetulla", de:"Augenbraue", note:"Tosk: vetull", cat:"trupi" },
  { id:549, gheg:"qerpik / qerpiku", de:"Wimper", note:"Tosk: qerpik", cat:"trupi" },
  { id:550, gheg:"hundë / hunda", de:"Nase", note:"Tosk: hundë", cat:"trupi" },
  { id:551, gheg:"vesh / veshi", de:"Ohr", note:"Tosk: vesh", cat:"trupi" },
  { id:552, gheg:"veshët", de:"Ohren (Pl.)", note:"Tosk: veshët", cat:"trupi" },
  { id:553, gheg:"gojë / goja", de:"Mund", note:"Tosk: gojë", cat:"trupi" },
  { id:554, gheg:"buzë / buzët", de:"Lippen", note:"Tosk: buzë", cat:"trupi" },
  { id:555, gheg:"dhëmb / dhëmbi", de:"Zahn", note:"Tosk: dhëmb", cat:"trupi" },
  { id:556, gheg:"dhëmbët", de:"Zähne (Pl.)", note:"Tosk: dhëmbët", cat:"trupi" },
  { id:557, gheg:"gjuhë / gjuha", de:"Zunge / Sprache", note:"Tosk: gjuhë", cat:"trupi" },
  { id:558, gheg:"fyt / fyti", de:"Hals / Rachen", note:"Tosk: fyt", cat:"trupi" },
  { id:559, gheg:"qafë / qafa", de:"Hals / Nacken", note:"Tosk: qafë", cat:"trupi" },
  { id:560, gheg:"sup / supi", de:"Schulter", note:"Tosk: sup", cat:"trupi" },
  { id:561, gheg:"krah / krahu", de:"Arm", note:"Tosk: krah", cat:"trupi" },
  { id:562, gheg:"bërryl / bërryli", de:"Ellenbogen", note:"Tosk: bërryl", cat:"trupi" },
  { id:563, gheg:"parakrah", de:"Unterarm", note:"Tosk: parakrah", cat:"trupi" },
  { id:564, gheg:"dorë / dora", de:"Hand", note:"Tosk: dorë", cat:"trupi" },
  { id:565, gheg:"dorë e djathtë", de:"rechte Hand", note:"Tosk: dorë e djathtë", cat:"trupi" },
  { id:566, gheg:"dorë e majtë", de:"linke Hand", note:"Tosk: dorë e majtë", cat:"trupi" },
  { id:567, gheg:"gisht / gishti", de:"Finger", note:"Tosk: gisht", cat:"trupi" },
  { id:568, gheg:"gishtërinjtë", de:"Finger (Pl.)", note:"[GHEG] Tosk: gishtërinjtë", cat:"trupi" },
  { id:569, gheg:"gisht i madh", de:"Daumen", note:"Tosk: gisht i madh", cat:"trupi" },
  { id:570, gheg:"gisht tregues", de:"Zeigefinger", note:"Tosk: gisht tregues", cat:"trupi" },
  { id:571, gheg:"thua / thoi", de:"Nagel (Fingernagel)", note:"[GHEG] Tosk: thua", cat:"trupi" },
  { id:572, gheg:"grusht / grushti", de:"Faust", note:"Tosk: grusht", cat:"trupi" },
  { id:573, gheg:"kyç i dorës", de:"Handgelenk", note:"Tosk: kyç i dorës", cat:"trupi" },
  { id:574, gheg:"bark / barku", de:"Bauch", note:"Tosk: bark", cat:"trupi" },
  { id:575, gheg:"kërthizë", de:"Nabel", note:"Tosk: kërthizë", cat:"trupi" },
  { id:576, gheg:"gjoks / gjoksi", de:"Brust (Brustkorb)", note:"Tosk: gjoks", cat:"trupi" },
  { id:577, gheg:"gji / gjiri", de:"Brust (weiblich)", note:"Tosk: gji", cat:"trupi" },
  { id:578, gheg:"shpinë", de:"Rücken", note:"Tosk: shpinë", cat:"trupi" },
  { id:579, gheg:"kurriz", de:"Rückgrat / Wirbelsäule", note:"Tosk: kurriz", cat:"trupi" },
  { id:580, gheg:"bel / beli", de:"Taille", note:"Tosk: bel", cat:"trupi" },
  { id:581, gheg:"ijë", de:"Hüfte", note:"Tosk: ijë", cat:"trupi" },
  { id:582, gheg:"vithe / vithet", de:"Gesäß / Po", note:"Tosk: vithe", cat:"trupi" },
  { id:583, gheg:"prapanicë", de:"Hintern (informell)", note:"Tosk: prapanicë", cat:"trupi" },
  { id:584, gheg:"këmbë / këmba", de:"Bein / Fuß", note:"Tosk: këmbë (gleich)", cat:"trupi" },
  { id:585, gheg:"kofshë / kofsha", de:"Oberschenkel", note:"Tosk: kofshë", cat:"trupi" },
  { id:586, gheg:"gju / gjuri", de:"Knie", note:"Tosk: gju (gleich)", cat:"trupi" },
  { id:587, gheg:"kërc / kërci", de:"Schienbein", note:"Tosk: kërc", cat:"trupi" },
  { id:588, gheg:"kyç i këmbës", de:"Knöchel", note:"Tosk: kyç i këmbës", cat:"trupi" },
  { id:589, gheg:"thembra", de:"Ferse", note:"Tosk: thembër", cat:"trupi" },
  { id:590, gheg:"shputë / shputa", de:"Fußsohle", note:"Tosk: shputë", cat:"trupi" },
  { id:591, gheg:"gisht i këmbës", de:"Zeh", note:"Tosk: gisht i këmbës", cat:"trupi" },
  { id:592, gheg:"gishtërinj të këmbëve", de:"Zehen", note:"Tosk: gishtërinj të këmbëve", cat:"trupi" },
  { id:593, gheg:"lëkurë / lëkura", de:"Haut", note:"Tosk: lëkurë", cat:"trupi" },
  { id:594, gheg:"mish (i trupit)", de:"Fleisch (des Körpers)", note:"Tosk: mish", cat:"trupi" },
  { id:595, gheg:"gjak / gjaku", de:"Blut", note:"Tosk: gjak", cat:"trupi" },
  { id:596, gheg:"zemër / zêmra", de:"Herz", note:"[GHEG] nasal: zêmër; Tosk: zemër", cat:"trupi" },
  { id:597, gheg:"mëlçi", de:"Leber", note:"Tosk: mëlçi", cat:"trupi" },
  { id:598, gheg:"veshkë", de:"Niere", note:"Tosk: veshkë", cat:"trupi" },
  { id:599, gheg:"mushkëri", de:"Lunge", note:"Tosk: mushkëri", cat:"trupi" },
  { id:600, gheg:"stomak", de:"Magen", note:"Tosk: stomak", cat:"trupi" },
  { id:601, gheg:"zorrë / zorrët", de:"Darm", note:"Tosk: zorrë", cat:"trupi" },
  { id:602, gheg:"kockë / kocka", de:"Knochen", note:"Tosk: kockë", cat:"trupi" },
  { id:603, gheg:"shtyllë kurrizore", de:"Wirbelsäule", note:"Tosk: shtyllë kurrizore", cat:"trupi" },
  { id:604, gheg:"trun / truni", de:"Gehirn", note:"[GHEG] Tosk: tru", cat:"trupi" },
  { id:605, gheg:"nerv / nervi", de:"Nerv", note:"Tosk: nerv", cat:"trupi" },
  { id:606, gheg:"shëndet / shëndeti", de:"Gesundheit", note:"Tosk: shëndet", cat:"trupi" },
  { id:607, gheg:"i shëndetshëm / e shëndetshme", de:"gesund", note:"Tosk: i shëndetshëm", cat:"trupi" },
  { id:608, gheg:"sëmunë / sëmunët", de:"krank", note:"[GHEG] Tosk: i sëmurë", cat:"trupi" },
  { id:609, gheg:"i sëmurë", de:"krank", note:"Tosk: i sëmurë", cat:"trupi" },
  { id:610, gheg:"sëmundje", de:"Krankheit", note:"Tosk: sëmundje", cat:"trupi" },
  { id:611, gheg:"mjek / mjeku", de:"Arzt", note:"Tosk: mjek", cat:"trupi" },
  { id:612, gheg:"mjeke", de:"Ärztin", note:"Tosk: mjeke", cat:"trupi" },
  { id:613, gheg:"spital / spitali", de:"Krankenhaus", note:"Tosk: spital", cat:"trupi" },
  { id:614, gheg:"klinikë", de:"Klinik", note:"Tosk: klinikë", cat:"trupi" },
  { id:615, gheg:"ambulantë", de:"Ambulanz / Praxis", note:"Tosk: ambulantë", cat:"trupi" },
  { id:616, gheg:"farmaci", de:"Apotheke", note:"Tosk: farmaci", cat:"trupi" },
  { id:617, gheg:"ilaç / ilaçi", de:"Medikament", note:"Tosk: ilaç", cat:"trupi" },
  { id:618, gheg:"tabletë", de:"Tablette", note:"Tosk: tabletë", cat:"trupi" },
  { id:619, gheg:"shurup", de:"Hustensaft / Sirup", note:"Tosk: shurup", cat:"trupi" },
  { id:620, gheg:"vaksinë", de:"Impfung", note:"Tosk: vaksinë", cat:"trupi" },
  { id:621, gheg:"infermier / infermieri", de:"Krankenpfleger", note:"Tosk: infermier", cat:"trupi" },
  { id:622, gheg:"infermiere", de:"Krankenschwester", note:"Tosk: infermiere", cat:"trupi" },
  { id:623, gheg:"operacion / operacioni", de:"Operation", note:"Tosk: operacion", cat:"trupi" },
  { id:624, gheg:"kontroll / kontrolli", de:"Untersuchung / Check-up", note:"Tosk: kontroll", cat:"trupi" },
  { id:625, gheg:"analizë", de:"Analyse / Bluttest", note:"Tosk: analizë", cat:"trupi" },
  { id:626, gheg:"gjakmarrje", de:"Blutabnahme", note:"Tosk: marrje gjaku", cat:"trupi" },
  { id:627, gheg:"recept / receta", de:"Rezept", note:"Tosk: recetë", cat:"trupi" },
  { id:628, gheg:"termometër", de:"Thermometer", note:"Tosk: termometër", cat:"trupi" },
  { id:629, gheg:"presion / presioni", de:"Blutdruck", note:"Tosk: presion", cat:"trupi" },
  { id:630, gheg:"presion i lartë", de:"hoher Blutdruck", note:"Tosk: presion i lartë", cat:"trupi" },
  { id:631, gheg:"presion i ulët", de:"niedriger Blutdruck", note:"Tosk: presion i ulët", cat:"trupi" },
  { id:632, gheg:"dhimbje", de:"Schmerz", note:"Tosk: dhimbje", cat:"trupi" },
  { id:633, gheg:"dhimbje koke", de:"Kopfschmerzen", note:"Tosk: dhimbje koke", cat:"trupi" },
  { id:634, gheg:"dhimbje barku", de:"Bauchschmerzen", note:"Tosk: dhimbje barku", cat:"trupi" },
  { id:635, gheg:"dhimbje dhëmbi", de:"Zahnschmerzen", note:"Tosk: dhimbje dhëmbi", cat:"trupi" },
  { id:636, gheg:"dhimbje fyti", de:"Halsschmerzen", note:"Tosk: dhimbje fyti", cat:"trupi" },
  { id:637, gheg:"kollë / kolla", de:"Husten", note:"Tosk: kollë", cat:"trupi" },
  { id:638, gheg:"ftohje / ftohja", de:"Erkältung", note:"Tosk: ftohje", cat:"trupi" },
  { id:639, gheg:"grip / gripi", de:"Grippe", note:"Tosk: grip", cat:"trupi" },
  { id:640, gheg:"koronë / corona", de:"Corona", note:"Tosk: koronë", cat:"trupi" },
  { id:641, gheg:"ethe / ethet", de:"Fieber", note:"Tosk: ethe", cat:"trupi" },
  { id:642, gheg:"temperaturë", de:"Temperatur / Fieber", note:"Tosk: temperaturë", cat:"trupi" },
  { id:643, gheg:"lodhje", de:"Müdigkeit / Erschöpfung", note:"Tosk: lodhje", cat:"trupi" },
  { id:644, gheg:"i lodhun / e lodhët", de:"müde", note:"[GHEG] Tosk: i lodhur", cat:"trupi" },
  { id:645, gheg:"plagë / plaga", de:"Wunde", note:"Tosk: plagë", cat:"trupi" },
  { id:646, gheg:"gjakosje", de:"Blutung", note:"Tosk: gjakosje", cat:"trupi" },
  { id:647, gheg:"thyerje", de:"Bruch (Knochenbruch)", note:"Tosk: thyerje", cat:"trupi" },
  { id:648, gheg:"frakturë", de:"Fraktur", note:"Tosk: frakturë", cat:"trupi" },
  { id:649, gheg:"suva", de:"Gips", note:"Tosk: suva", cat:"trupi" },
  { id:650, gheg:"fashë", de:"Verband", note:"Tosk: fashë", cat:"trupi" },
  { id:651, gheg:"garzë", de:"Gaze / Mullbinde", note:"Tosk: garzë", cat:"trupi" },
  { id:652, gheg:"allçi", de:"Pflaster (Heftpflaster)", note:"[GHEG] Tosk: fashë ngjitëse", cat:"trupi" },
  { id:653, gheg:"shtatzanë / shtatzënë", de:"schwanger", note:"[GHEG] Tosk: shtatzënë", cat:"trupi" },
  { id:654, gheg:"shtatzani", de:"Schwangerschaft", note:"Tosk: shtatzëni", cat:"trupi" },
  { id:655, gheg:"lindje", de:"Geburt", note:"Tosk: lindje", cat:"trupi" },
  { id:656, gheg:"paaftësi", de:"Behinderung", note:"Tosk: paaftësi", cat:"trupi" },
  { id:657, gheg:"alergji", de:"Allergie", note:"Tosk: alergji", cat:"trupi" },
  { id:658, gheg:"diabet", de:"Diabetes", note:"Tosk: diabet", cat:"trupi" },
  { id:659, gheg:"kancer", de:"Krebs", note:"Tosk: kancer", cat:"trupi" },
  { id:660, gheg:"sulm në zemër", de:"Herzinfarkt", note:"Tosk: sulm në zemër", cat:"trupi" },
  { id:661, gheg:"goditje në tru", de:"Schlaganfall", note:"Tosk: goditje në tru", cat:"trupi" },
  { id:662, gheg:"qëndrim në spital", de:"Krankenhausaufenthalt", note:"Tosk: qëndrim në spital", cat:"trupi" },
  { id:663, gheg:"sigurim shëndetësor", de:"Krankenversicherung", note:"Tosk: sigurim shëndetësor", cat:"trupi" },
  { id:664, gheg:"mjek i përgjithshëm", de:"Allgemeinmediziner", note:"Tosk: mjek i përgjithshëm", cat:"trupi" },
  { id:665, gheg:"dentist / dentisti", de:"Zahnarzt", note:"Tosk: dentist", cat:"trupi" },
  { id:666, gheg:"optiker", de:"Optiker", note:"Tosk: optik", cat:"trupi" },
  // ── EMOCIONET (94 Wörter) ──
  { id:667, gheg:"ndjej / ndiej", de:"fühlen", note:"[GHEG] Tosk: ndiej", cat:"emocionet" },
  { id:668, gheg:"ndjenjë", de:"Gefühl", note:"Tosk: ndjenjë", cat:"emocionet" },
  { id:669, gheg:"emocion / emocioni", de:"Emotion", note:"Tosk: emocion", cat:"emocionet" },
  { id:670, gheg:"gëzim / gëzimi", de:"Freude", note:"Tosk: gëzim", cat:"emocionet" },
  { id:671, gheg:"i gëzuem / e gëzueme", de:"fröhlich", note:"[GHEG] Tosk: i gëzuar", cat:"emocionet" },
  { id:672, gheg:"lumturi", de:"Glück", note:"Tosk: lumturi", cat:"emocionet" },
  { id:673, gheg:"i lumtun / e lumtun", de:"glücklich", note:"[GHEG] Tosk: i lumtur", cat:"emocionet" },
  { id:674, gheg:"kënaqësi", de:"Vergnügen / Zufriedenheit", note:"Tosk: kënaqësi", cat:"emocionet" },
  { id:675, gheg:"i kënaqun / e kënaqun", de:"zufrieden", note:"[GHEG] Tosk: i kënaqur", cat:"emocionet" },
  { id:676, gheg:"dashuri", de:"Liebe", note:"Tosk: dashuri", cat:"emocionet" },
  { id:677, gheg:"dashnohem", de:"sich verlieben", note:"Tosk: dashurohem", cat:"emocionet" },
  { id:678, gheg:"i dashun / e dashun", de:"lieb / geliebt", note:"[GHEG] Tosk: i dashur", cat:"emocionet" },
  { id:679, gheg:"e dashura", de:"die Geliebte / Freundin", note:"Tosk: e dashura", cat:"emocionet" },
  { id:680, gheg:"i dashuri", de:"der Geliebte / Freund", note:"Tosk: i dashuri", cat:"emocionet" },
  { id:681, gheg:"përkëdhelje", de:"Zärtlichkeit", note:"Tosk: përkëdhelje", cat:"emocionet" },
  { id:682, gheg:"mall / malli", de:"Sehnsucht / Heimweh", note:"Tosk: mall", cat:"emocionet" },
  { id:683, gheg:"më mungon", de:"du fehlst mir", note:"Tosk: më mungon", cat:"emocionet" },
  { id:684, gheg:"trishtim", de:"Traurigkeit", note:"Tosk: trishtim", cat:"emocionet" },
  { id:685, gheg:"i trishtuem / e trishtueme", de:"traurig", note:"[GHEG] Tosk: i trishtuar", cat:"emocionet" },
  { id:686, gheg:"hidhërim", de:"Kummer / Bitterkeit", note:"Tosk: hidhërim", cat:"emocionet" },
  { id:687, gheg:"i hidhëruem", de:"bekümmert / traurig", note:"[GHEG] Tosk: i hidhëruar", cat:"emocionet" },
  { id:688, gheg:"qaj", de:"weinen", note:"Tosk: qaj", cat:"emocionet" },
  { id:689, gheg:"vajtoj", de:"klagen / wehklagen", note:"Tosk: vajtoj", cat:"emocionet" },
  { id:690, gheg:"lot / loti", de:"Träne", note:"Tosk: lot", cat:"emocionet" },
  { id:691, gheg:"lotët", de:"Tränen (Pl.)", note:"Tosk: lotët", cat:"emocionet" },
  { id:692, gheg:"dëshpërim", de:"Verzweiflung", note:"Tosk: dëshpërim", cat:"emocionet" },
  { id:693, gheg:"i dëshpëruem", de:"verzweifelt", note:"[GHEG] Tosk: i dëshpëruar", cat:"emocionet" },
  { id:694, gheg:"shpresë", de:"Hoffnung", note:"Tosk: shpresë", cat:"emocionet" },
  { id:695, gheg:"shpresoj", de:"hoffen", note:"Tosk: shpresoj", cat:"emocionet" },
  { id:696, gheg:"i shpresëshëm", de:"hoffnungsvoll", note:"Tosk: i shpresëshëm", cat:"emocionet" },
  { id:697, gheg:"pa shpresë", de:"hoffnungslos", note:"Tosk: pa shpresë", cat:"emocionet" },
  { id:698, gheg:"zemërim / zëmërim", de:"Wut / Zorn", note:"[GHEG] Tosk: zemërim", cat:"emocionet" },
  { id:699, gheg:"i zemëruem / i zëmëruem", de:"wütend", note:"[GHEG] Tosk: i zemëruar", cat:"emocionet" },
  { id:700, gheg:"inat / inati", de:"Trotz / Ärger", note:"Tosk: inat", cat:"emocionet" },
  { id:701, gheg:"me inat", de:"mit Absicht / aus Trotz", note:"Tosk: me inat", cat:"emocionet" },
  { id:702, gheg:"mërzitje", de:"Langeweile / Genervtheit", note:"Tosk: mërzitje", cat:"emocionet" },
  { id:703, gheg:"i mërzitun / e mërzitun", de:"gelangweilt / genervt", note:"[GHEG] Tosk: i mërzitur", cat:"emocionet" },
  { id:704, gheg:"urrejtje", de:"Hass", note:"Tosk: urrejtje", cat:"emocionet" },
  { id:705, gheg:"urrej", de:"hassen", note:"Tosk: urrej", cat:"emocionet" },
  { id:706, gheg:"dyshim", de:"Zweifel / Verdacht", note:"Tosk: dyshim", cat:"emocionet" },
  { id:707, gheg:"dyshoj", de:"zweifeln / verdächtigen", note:"Tosk: dyshoj", cat:"emocionet" },
  { id:708, gheg:"frikë / frika", de:"Angst", note:"Tosk: frikë", cat:"emocionet" },
  { id:709, gheg:"kam frikë", de:"ich habe Angst", note:"Tosk: kam frikë", cat:"emocionet" },
  { id:710, gheg:"i frikësuem", de:"verängstigt", note:"[GHEG] Tosk: i frikësuar", cat:"emocionet" },
  { id:711, gheg:"tmerr", de:"Schrecken / Entsetzen", note:"Tosk: tmerr", cat:"emocionet" },
  { id:712, gheg:"neveri", de:"Ekel", note:"Tosk: neveri", cat:"emocionet" },
  { id:713, gheg:"i neveritshëm", de:"eklig", note:"Tosk: i neveritshëm", cat:"emocionet" },
  { id:714, gheg:"shok / shoku", de:"Schock", note:"Tosk: shok", cat:"emocionet" },
  { id:715, gheg:"befasi", de:"Überraschung", note:"Tosk: befasi", cat:"emocionet" },
  { id:716, gheg:"i befasuem", de:"überrascht", note:"[GHEG] Tosk: i befasuar", cat:"emocionet" },
  { id:717, gheg:"çudi", de:"Wunder / Erstaunen", note:"Tosk: çudi", cat:"emocionet" },
  { id:718, gheg:"kureshtje", de:"Neugier", note:"Tosk: kureshtje", cat:"emocionet" },
  { id:719, gheg:"kureshtar", de:"neugierig", note:"Tosk: kureshtar", cat:"emocionet" },
  { id:720, gheg:"i interesuem", de:"interessiert", note:"[GHEG] Tosk: i interesuar", cat:"emocionet" },
  { id:721, gheg:"mosinteresim", de:"Desinteresse", note:"Tosk: mosinteresim", cat:"emocionet" },
  { id:722, gheg:"gjakftohtësi", de:"Gelassenheit", note:"Tosk: gjakftohtësi", cat:"emocionet" },
  { id:723, gheg:"i qetë / e qetë", de:"ruhig", note:"Tosk: i qetë", cat:"emocionet" },
  { id:724, gheg:"qetësi", de:"Ruhe", note:"Tosk: qetësi", cat:"emocionet" },
  { id:725, gheg:"shqetësim", de:"Sorge / Unruhe", note:"Tosk: shqetësim", cat:"emocionet" },
  { id:726, gheg:"i shqetësuem", de:"besorgt / unruhig", note:"[GHEG] Tosk: i shqetësuar", cat:"emocionet" },
  { id:727, gheg:"ankth", de:"Angst / Beklemmung", note:"Tosk: ankth", cat:"emocionet" },
  { id:728, gheg:"stres / stresi", de:"Stress", note:"Tosk: stres", cat:"emocionet" },
  { id:729, gheg:"i stresuem", de:"gestresst", note:"[GHEG] Tosk: i stresuar", cat:"emocionet" },
  { id:730, gheg:"nervoz", de:"nervös", note:"Tosk: nervoz (gleich); 'nervozë' wäre grammatisch falsch", cat:"emocionet" },
  { id:731, gheg:"i çartun / e çartun", de:"wütend (regional)", note:"[GHEG] regional", cat:"emocionet" },
  { id:732, gheg:"i hidhët / e hidhët", de:"bitter (auch emotional)", note:"Tosk: i hidhur", cat:"emocionet" },
  { id:733, gheg:"i ëmbël", de:"süß (auch emotional)", note:"Tosk: i ëmbël", cat:"emocionet" },
  { id:734, gheg:"zili / zilia", de:"Neid", note:"Tosk: zili", cat:"emocionet" },
  { id:735, gheg:"xhelozi", de:"Eifersucht", note:"Tosk: xhelozi", cat:"emocionet" },
  { id:736, gheg:"xheloz", de:"eifersüchtig", note:"Tosk: xheloz", cat:"emocionet" },
  { id:737, gheg:"krenari", de:"Stolz", note:"Tosk: krenari", cat:"emocionet" },
  { id:738, gheg:"krenar", de:"stolz", note:"Tosk: krenar", cat:"emocionet" },
  { id:739, gheg:"turp / turpi", de:"Scham", note:"Tosk: turp", cat:"emocionet" },
  { id:740, gheg:"i turpëruem", de:"beschämt", note:"[GHEG] Tosk: i turpëruar", cat:"emocionet" },
  { id:741, gheg:"faj / faji", de:"Schuld", note:"Tosk: faj", cat:"emocionet" },
  { id:742, gheg:"kam faj", de:"ich habe Schuld", note:"Tosk: kam faj", cat:"emocionet" },
  { id:743, gheg:"pendim", de:"Reue", note:"Tosk: pendim", cat:"emocionet" },
  { id:744, gheg:"pendohem", de:"bereuen", note:"Tosk: pendohem", cat:"emocionet" },
  { id:745, gheg:"siguri", de:"Sicherheit / Zuversicht", note:"Tosk: siguri", cat:"emocionet" },
  { id:746, gheg:"i sigurt", de:"sicher (Gefühl)", note:"Tosk: i sigurt", cat:"emocionet" },
  { id:747, gheg:"pasiguri", de:"Unsicherheit", note:"Tosk: pasiguri", cat:"emocionet" },
  { id:748, gheg:"i pasigurt", de:"unsicher", note:"Tosk: i pasigurt", cat:"emocionet" },
  { id:749, gheg:"përulësi", de:"Demut", note:"Tosk: përulësi", cat:"emocionet" },
  { id:750, gheg:"mirënjohje", de:"Dankbarkeit", note:"Tosk: mirënjohje", cat:"emocionet" },
  { id:751, gheg:"mirënjohës", de:"dankbar", note:"Tosk: mirënjohës", cat:"emocionet" },
  { id:752, gheg:"dhembshuri", de:"Mitgefühl", note:"Tosk: dhembshuri", cat:"emocionet" },
  { id:753, gheg:"dhembshues", de:"mitfühlend", note:"Tosk: dhembshues", cat:"emocionet" },
  { id:754, gheg:"mëshirë", de:"Gnade / Barmherzigkeit", note:"Tosk: mëshirë", cat:"emocionet" },
  { id:755, gheg:"falënderim", de:"Dank", note:"Tosk: falënderim", cat:"emocionet" },
  { id:756, gheg:"faleminderit", de:"danke", note:"Tosk: faleminderit", cat:"emocionet" },
  { id:757, gheg:"ndihmë", de:"Hilfe", note:"Tosk: ndihmë", cat:"emocionet" },
  { id:758, gheg:"besim", de:"Vertrauen", note:"Tosk: besim", cat:"emocionet" },
  { id:759, gheg:"kam besim", de:"ich vertraue", note:"Tosk: kam besim", cat:"emocionet" },
  { id:760, gheg:"mosbesim", de:"Misstrauen", note:"Tosk: mosbesim", cat:"emocionet" },
  // ── RUTINA (62 Wörter) ──
  { id:761, gheg:"rutinë / rutina", de:"Routine", note:"Tosk: rutinë", cat:"rutina" },
  { id:762, gheg:"ditë / dita", de:"Tag", note:"Tosk: ditë", cat:"rutina" },
  { id:763, gheg:"natë / nata", de:"Nacht", note:"Tosk: natë", cat:"rutina" },
  { id:764, gheg:"mëngjes", de:"Morgen", note:"Tosk: mëngjes", cat:"rutina" },
  { id:765, gheg:"paraditë", de:"Vormittag", note:"Tosk: paraditë", cat:"rutina" },
  { id:766, gheg:"pasditë", de:"Nachmittag", note:"Tosk: pasdite", cat:"rutina" },
  { id:767, gheg:"mbrëmje", de:"Abend", note:"Tosk: mbrëmje", cat:"rutina" },
  { id:768, gheg:"çohem", de:"aufstehen", note:"Tosk: çohem", cat:"rutina" },
  { id:769, gheg:"lahem / laj", de:"waschen (sich waschen)", note:"Tosk: lahem / laj", cat:"rutina" },
  { id:770, gheg:"laj fytyrën", de:"Gesicht waschen", note:"Tosk: laj fytyrën", cat:"rutina" },
  { id:771, gheg:"laj dhëmbët", de:"Zähne putzen", note:"Tosk: laj dhëmbët", cat:"rutina" },
  { id:772, gheg:"vishem", de:"sich anziehen", note:"Tosk: vishem", cat:"rutina" },
  { id:773, gheg:"kreh flokët", de:"Haare kämmen", note:"Tosk: kreh flokët", cat:"rutina" },
  { id:774, gheg:"bëj kafe", de:"Kaffee machen", note:"[GHEG] Tosk: bëj kafe", cat:"rutina" },
  { id:775, gheg:"ha mëngjes", de:"frühstücken", note:"Tosk: ha mëngjes", cat:"rutina" },
  { id:776, gheg:"nisem", de:"aufbrechen / losgehen", note:"Tosk: nisem", cat:"rutina" },
  { id:777, gheg:"shkoj në punë", de:"zur Arbeit gehen", note:"Tosk: shkoj në punë", cat:"rutina" },
  { id:778, gheg:"shkoj në shkollë", de:"zur Schule gehen", note:"Tosk: shkoj në shkollë", cat:"rutina" },
  { id:779, gheg:"kthehem në shpi", de:"nach Hause kommen", note:"[GHEG] Tosk: kthehem në shtëpi", cat:"rutina" },
  { id:780, gheg:"ha drekë", de:"zu Mittag essen", note:"Tosk: ha drekë", cat:"rutina" },
  { id:781, gheg:"ha darkë", de:"zu Abend essen", note:"Tosk: ha darkë", cat:"rutina" },
  { id:782, gheg:"përgatis ushqim", de:"Essen zubereiten", note:"Tosk: përgatis ushqim", cat:"rutina" },
  { id:783, gheg:"bëj pazar", de:"einkaufen gehen", note:"Tosk: bëj pazar", cat:"rutina" },
  { id:784, gheg:"pastroj shpinë", de:"Haus putzen", note:"[GHEG] Tosk: pastroj shtëpinë", cat:"rutina" },
  { id:785, gheg:"laj enët", de:"Geschirr spülen", note:"Tosk: laj enët", cat:"rutina" },
  { id:786, gheg:"laj rroba", de:"Wäsche waschen", note:"Tosk: laj rroba", cat:"rutina" },
  { id:787, gheg:"hekuros", de:"bügeln", note:"Tosk: hekuros", cat:"rutina" },
  { id:788, gheg:"palos rrobat", de:"Kleidung zusammenlegen", note:"Tosk: palos rrobat", cat:"rutina" },
  { id:789, gheg:"bëj shtratin", de:"Bett machen", note:"Tosk: rregulloj shtratin", cat:"rutina" },
  { id:790, gheg:"pushoj", de:"ausruhen", note:"Tosk: pushoj", cat:"rutina" },
  { id:791, gheg:"fle / fjet", de:"schlafen", note:"[GHEG] Tosk: fle", cat:"rutina" },
  { id:792, gheg:"fjet / flej", de:"ich schlafe", note:"[GHEG] Tosk: fle", cat:"rutina" },
  { id:793, gheg:"bie në gjumë", de:"einschlafen", note:"Tosk: bie në gjumë", cat:"rutina" },
  { id:794, gheg:"ëndërr / ëndrra", de:"Traum", note:"Tosk: ëndërr", cat:"rutina" },
  { id:795, gheg:"ëndërroj", de:"träumen", note:"Tosk: ëndërroj", cat:"rutina" },
  { id:796, gheg:"zgjohem", de:"aufwachen", note:"Tosk: zgjohem", cat:"rutina" },
  { id:797, gheg:"bëj dush", de:"duschen", note:"Tosk: bëj dush", cat:"rutina" },
  { id:798, gheg:"krej / krehem", de:"kämmen", note:"[GHEG] Tosk: krehem", cat:"rutina" },
  { id:799, gheg:"rruhem", de:"rasieren", note:"Tosk: rruhem", cat:"rutina" },
  { id:800, gheg:"bëj gati", de:"fertig machen / vorbereiten", note:"Tosk: bëj gati", cat:"rutina" },
  { id:801, gheg:"jam me nxitim", de:"ich habe es eilig", note:"Tosk: jam me nxitim", cat:"rutina" },
  { id:802, gheg:"nxitim", de:"Eile", note:"Tosk: nxitim", cat:"rutina" },
  { id:803, gheg:"vonë", de:"spät", note:"Tosk: vonë", cat:"rutina" },
  { id:804, gheg:"herët", de:"früh", note:"Tosk: herët", cat:"rutina" },
  { id:805, gheg:"kohë / koha", de:"Zeit", note:"Tosk: kohë", cat:"rutina" },
  { id:806, gheg:"sot", de:"heute", note:"Tosk: sot", cat:"rutina" },
  { id:807, gheg:"nesër", de:"morgen", note:"Tosk: nesër", cat:"rutina" },
  { id:808, gheg:"pardje / pardje", de:"vorgestern", note:"[GHEG] Tosk: pardje", cat:"rutina" },
  { id:809, gheg:"tash / tani", de:"jetzt", note:"[GHEG] tash! Tosk: tani", cat:"rutina" },
  { id:810, gheg:"atëherë", de:"dann / damals", note:"Tosk: atëherë", cat:"rutina" },
  { id:811, gheg:"pastaj", de:"danach", note:"Tosk: pastaj", cat:"rutina" },
  { id:812, gheg:"kurrë", de:"nie", note:"Tosk: kurrë", cat:"rutina" },
  { id:813, gheg:"gjithmonë", de:"immer", note:"Tosk: gjithmonë", cat:"rutina" },
  { id:814, gheg:"ndonjëherë", de:"manchmal", note:"Tosk: ndonjëherë", cat:"rutina" },
  { id:815, gheg:"shpesh", de:"oft", note:"Tosk: shpesh", cat:"rutina" },
  { id:816, gheg:"rrallë", de:"selten", note:"Tosk: rrallë", cat:"rutina" },
  { id:817, gheg:"ditën", de:"tagsüber", note:"Tosk: ditën", cat:"rutina" },
  { id:818, gheg:"natën", de:"nachts", note:"Tosk: natën", cat:"rutina" },
  { id:819, gheg:"javë / java", de:"Woche", note:"Tosk: javë", cat:"rutina" },
  { id:820, gheg:"muaj / muaji", de:"Monat", note:"Tosk: muaj", cat:"rutina" },
  { id:821, gheg:"vit / viti", de:"Jahr", note:"Tosk: vit", cat:"rutina" },
  { id:822, gheg:"kalendar", de:"Kalender", note:"Tosk: kalendar", cat:"rutina" },
];

// Gesamt: 907 Wörter (822 + 85 Schimpfwörter)

const LEARN_CAT_LABELS = {
  alle: "Alle (907)",
  "familje": "familje (70)",
  "shtepi": "shtepi (90)",
  "mobilje": "mobilje (86)",
  "ushqim": "ushqim (219)",
  "rroba": "rroba (77)",
  "trupi": "trupi (124)",
  "emocionet": "emocionet (94)",
  "rutina": "rutina (62)",
  "schimpf": "schimpf (85)",
};
